import test from 'node:test';
import assert from 'node:assert/strict';
import {createRecurringStore,recurringItems,parseRecurring} from '../src/hanni/js/calendar-recurring-store.js';
function setup(){let raw=null,fail=false,now=new Date(2026,8,13,12),sequence=0;const invoke=async(command,args)=>{if(command==='get_ui_state')return raw;if(fail)throw Error('offline');raw=args.value;};return {store:createRecurringStore(invoke,{now:()=>now,uuid:()=>String(++sequence)}),second:()=>createRecurringStore(invoke,{now:()=>now,uuid:()=>String(++sequence)}),raw:()=>raw,fail:()=>{fail=true;},advance:()=>{now=new Date(2026,8,14,12);}};}
const action={kind:'action',title:'Учебный курс',weekdays:[0,1,2,3,4,5,6],startsOn:'2026-09-13',endsOn:'2026-09-15'};
test('fresh profile has no plans or personal seed; quantitative kind rejected',async()=>{const {store}=setup();assert.deepEqual((await store.read()).plans,[]);await assert.rejects(store.savePlan({...action,kind:'norm'}));});
test('course applies only to selected weekdays and inclusive dates',async()=>{const {store}=setup();const {state}=await store.savePlan({...action,weekdays:[0,2]});assert.equal(recurringItems(state,'2026-09-12').length,0);assert.equal(recurringItems(state,'2026-09-13').length,1);assert.equal(recurringItems(state,'2026-09-14').length,0);assert.equal(recurringItems(state,'2026-09-15').length,1);assert.equal(recurringItems(state,'2026-09-16').length,0);});
test('edit preserves historical title/status and updates today only',async()=>{const context=setup(),{store}=context;const {result:id}=await store.savePlan(action);await store.setStatus(id,'done');context.advance();await store.savePlan({...action,title:'Новое название'},id);const state=await store.read();assert.equal(recurringItems(state,'2026-09-13')[0].title,action.title);assert.equal(recurringItems(state,'2026-09-13')[0].status,'done');assert.equal(recurringItems(state,'2026-09-14')[0].title,'Новое название');assert.equal(recurringItems(state,'2026-09-14')[0].status,'pending');});
test('future observations and mismatched rule/action statuses rejected',async()=>{const {store}=setup();const {result:id}=await store.savePlan({...action,kind:'rule'});await assert.rejects(store.setStatus(id,'kept','2026-09-14'));await assert.rejects(store.setStatus(id,'done'));await store.setStatus(id,'broken');assert.equal(recurringItems(await store.read(),'2026-09-13')[0].status,'broken');await store.setStatus(id,'pending');assert.equal(recurringItems(await store.read(),'2026-09-13')[0].status,'pending');});
test('native failure retains previous snapshot',async()=>{const context=setup();const {result:id}=await context.store.savePlan(action);const raw=context.raw();context.fail();await assert.rejects(context.store.setStatus(id,'done'));assert.equal(context.raw(),raw);});
test('concurrent controllers serialize updates against latest snapshot',async()=>{const context=setup();await Promise.all([context.store.savePlan(action),context.second().savePlan({...action,title:'Вторая'})]);assert.equal((await context.store.read()).plans.length,2);});
test('new plan without start cannot appear before creation',async()=>{const {store}=setup();const {state}=await store.savePlan({...action,startsOn:''});assert.equal(recurringItems(state,'2026-09-12').length,0);});
test('invalid snapshots never silently reset data',()=>{assert.throws(()=>parseRecurring('{'));assert.throws(()=>parseRecurring('{"version":2,"plans":[],"days":{}}'));});
