const english = {
  "неизвестна": "unknown",
  "Задач пока нет.": "No tasks yet.",
  "Приёмка недоступна: подборка сохранена, задачи не показаны.": "Review is unavailable: the saved view is preserved, and tasks are hidden.",
  "Недоступная цель ({0})": "Unavailable goal ({0})",
  "Недоступная цель: {0}": "Unavailable goal: {0}",
  "Недоступно: {0}": "Unavailable: {0}",
  "Подборки задач": "Task views",
  " · изменено": " · modified",
  "Название подборки": "View name",
  "Изменить подборку": "Edit view",
  "Сохранятся фильтры, выбранные при открытии формы.": "The filters selected when this form opened will be saved.",
  "Удалить подборку": "Delete view",
  "Подтвердить удаление": "Confirm deletion",
  "Не удалять": "Keep view",
  "Сохранить текущие фильтры": "Save current filters",
  "Обновить подборки": "Refresh views",
  "Загружаем подборки…": "Loading views…",
  "Удалить подборку «{0}»? Задачи останутся.": "Delete the view “{0}”? Tasks will remain.",
  "Нельзя сохранить текущие фильтры: {0}": "Cannot save the current filters: {0}",
  "Подборка уже сохранена.": "The view is already saved.",
  "Идентификатор черновика уже занят. Отмените правку и создайте подборку заново.": "The draft ID is already in use. Cancel the edit and create the view again.",
  "Эта подборка изменилась или удалена. Отмените правку и откройте её заново.": "This view changed or was deleted. Cancel the edit and reopen it.",
  "Выбранная подборка удалена. Текущие фильтры сохранены на экране.": "The selected view was deleted. The current filters are preserved on screen.",
  "Не удалось загрузить подборки: {0} Нажмите «Обновить подборки».": "Could not load views: {0} Click Refresh views.",
  "Подборки изменились в другом окне. Нажмите «Обновить подборки»; черновик останется открытым.": "Views changed in another window. Click Refresh views; your draft will stay open.",
  "Не удалось сохранить подборку: {0} Черновик сохранён на экране.": "Could not save the view: {0} Your draft is preserved on screen.",
  "Укажите название до {0} символов.": "Enter a name of up to {0} characters.",
  "повторите попытку": "try again",
  "Фильтры вида повреждены.": "The view filters are corrupt.",
  "Сохранённый вид содержит неизвестный фильтр.": "The saved view contains an unknown filter.",
  "В сохранённом виде отсутствует фильтр.": "The saved view is missing a filter.",
  "Недопустимое значение фильтра «{0}».": "Invalid value for the “{0}” filter.",
  "Фильтр «{0}» слишком длинный.": "The “{0}” filter is too long.",
  "Сохранённый вид содержит неподдерживаемое значение фильтра.": "The saved view contains an unsupported filter value.",
  "Невозможно прочитать фильтры задач.": "Could not read the task filters.",
  "Сохранённый вид повреждён.": "The saved view is corrupt.",
  "Недопустимый идентификатор сохранённого вида.": "Invalid saved view ID.",
  "Название вида должно содержать от 1 до 80 символов.": "The view name must contain 1 to 80 characters.",
  "Формат сохранённых видов задач не поддерживается.": "The saved task view format is unsupported.",
  "Слишком много сохранённых видов задач.": "Too many saved task views.",
  "Идентификаторы сохранённых видов повторяются.": "Saved view IDs are duplicated.",
  "Не удалось подготовить сохранённые виды задач.": "Could not prepare the saved task views.",
  "Сохранённые виды задач превышают допустимый размер.": "Saved task views exceed the size limit.",
  "Не удалось прочитать сохранённые виды задач.": "Could not read the saved task views.",
  "Список сохранённых видов повреждён.": "The list of saved views is corrupt.",
  "Не удалось создать уникальный идентификатор вида.": "Could not create a unique view ID.",
  "Не удалось загрузить сохранённые виды задач.": "Could not load the saved task views.",
  "Неверная исходная версия сохранённых видов.": "Invalid original version of the saved views.",
  "Сохранённые виды изменились в другом окне. Загрузите их снова и повторите изменение.": "Saved views changed in another window. Reload them and retry the change.",
  "Не удалось сохранить виды задач.": "Could not save the task views.",

  "Работа ИИ": "AI work",
  "сообщил, что работает": "reported that they are working",
  "сообщил, что ожидает": "reported that they are waiting",
  "сообщил о завершении": "reported completion",
  "сообщил об ошибке": "reported an error",
  "сообщил об остановке": "reported stopping",
  "другой исполнитель": "another executor",
  "Подключение к исполнителю не подтверждено. По последнему отчёту. Время и актуальность неизвестны; текущее состояние не подтверждено.": "Executor connection is unconfirmed. Based on the last report. Time and freshness are unknown; the current state is unconfirmed.",
  "Нет связанных отчётов о работе ИИ. Регистрация задачи не означает запуск.": "No linked AI work reports. Task registration does not mean execution has started.",
  "По последнему отчёту{0}: исполнитель {1}.": "In the last report{0}, the executor {1}.",
  "Модель: {0} · этап: {1} · актуальность: {2}": "Model: {0} · stage: {1} · freshness: {2}",
  "не сообщена": "not reported",
  "не сообщён": "not reported",
  " Завершение задачи требует приёмки пользователем.": " Task completion requires user acceptance.",
  "Загружаем отчёты…": "Loading reports…",
  "Актуальность неизвестна: чтение отчётов завершилось ошибкой.": "Freshness is unknown: reading reports failed.",
  "Не удалось прочитать отчёты. Прежние данные скрыты.": "Could not read reports. Previous data is hidden.",

  "Настройки изменились. Нажми «Сохранить» ещё раз.": "Settings changed. Click Save again.",
  "Настройка «{0}» изменилась. Закрой и открой настройки, чтобы загрузить актуальные значения.": "The {0} setting changed. Close and reopen Settings to load the current values.",
  "Повреждённые настройки календаря не были применены.": "Corrupt calendar settings were not applied.",
  "Настройки изменились на другом устройстве. Нажми «Сохранить» ещё раз.": "Settings changed on another device. Click Save again.",
  "Стадия удалена": "Deleted stage",
  "Доступно {0} задач": "{0} tasks available",

  "Важная задача, запланированная на более ранний день.": "Important task planned for an earlier day.",
  "Ты отметил задачу как важную.": "You marked this task as important.",
  "Задача запланирована на более ранний день.": "Task planned for an earlier day.",
  "Задача запланирована на сегодня.": "Task planned for today.",
  "Задача без заданного срока.": "Task without a deadline.",
  "Утро — рутина ещё не отмечена.": "Morning: routine has not been marked yet.",
  "Время обеда — рутина ещё не отмечена.": "Lunchtime: routine has not been marked yet.",
  "Вечер — рутина ещё не отмечена.": "Evening: routine has not been marked yet.",
  "Можно сделать перерыв на еду — рутина ещё не отмечена.": "You can take a meal break: routine has not been marked yet.",
  "Необязательное дело на сегодня.": "Optional activity for today.",
  "Повторяющееся дело на сегодня.": "Recurring activity for today.",
  "Задача уже выполняется.": "Task is already running.",
  "Повторяющееся дело": "Recurring activity",
  "Выполнение уже запущено.": "Activity is already running.",
  "Рутина · отметка без таймера": "Routine · checkmark without a timer",
  "Рутина · с учётом времени": "Routine · with timing",
  "Некорректный ответ сервера.": "Invalid response.",
  "Список изменился. Проверь новую рекомендацию.": "The list changed. Check the new recommendation.",
  "Действие задачи недоступно.": "Task action is unavailable.",
  "Запуск рутины недоступен.": "Routine start is unavailable.",
  "Действие больше недоступно. Обнови список.": "Action is no longer available. Refresh the list.",
  "Ничего не нашлось. Измени поиск, цель или сферу.": "Nothing found. Change the search, goal or area.",
  "В этой сфере задач нет. Выбери другую сферу или создай задачу через «+ Создать».": "No tasks in this area. Choose another area or use + Create.",
  "Завершённых задач пока нет.": "No completed tasks yet.",
  "Все задачи распределены по дням.": "All tasks have a planned day.",
  "На сегодня задач нет.": "No tasks for today.",
  "Задач пока нет. Создай первую через «+ Создать».": "No tasks yet. Use + Create to add the first one.",
  "Перенести": "Move",
  "Переносим…": "Moving…",
  "перенести": "move",
  "Убираем даты…": "Clearing dates…",
  "убрать дату": "clear dates",
  "Завтра": "Tomorrow",
  "Вчера": "Yesterday",
  "Таймер идёт": "Timer running",
  "На паузе": "Paused",
  "Не начата": "Not started",
  "Таймер на паузе": "Timer paused",
  "Таймер не запущен": "Timer not started",
  "Моментальная": "Instant",
  "Отмечается одним нажатием, без таймера": "Marked with one click, without a timer",
  " · просрочено": " · overdue",
  "жду ответа": "waiting for a response",
  "Ожидает передачи исполнителю": "Awaiting dispatch to executor",
  "модель не сообщена": "model not reported",
  "Состояние приёмки не обновлено. Повтори чтение.": "Review status was not refreshed. Read it again.",
  "Действия": "Actions",
  "Не удалось прочитать наблюдения источников.": "Could not read source observations.",
  "Здесь показаны отчёты исполнителей; текущие обновления не подключены.": "Executor reports are shown here; live updates are not connected.",
  "Не удалось обновить задачи. Показан предыдущий список.": "Could not refresh tasks. The previous list is shown.",
  "Не удалось загрузить задачи. Это не означает, что список пуст.": "Could not load tasks. This does not mean the list is empty.",
  "Задача в работе.": "Task is running.",
  "Задача на паузе.": "Task is paused.",
  "Задача завершена.": "Task is completed.",
  "Не удалось выполнить действие.": "Could not apply action.",
  "Задача могла измениться": "The task may have changed",
  "Задачи могли измениться": "Tasks may have changed",
  "Не удалось перейти к следующему этапу. Повтори.": "Could not advance to the next stage. Try again.",
  "История отметок": "Checkmark history",
  "Других дел на сегодня нет": "No other activities for today",
  "На сегодня дел нет": "No activities for today",
  "Нет дел без отметки": "No unmarked activities",
  "Выполнено": "Completed",
  "Пропущено": "Skipped",
  "По желанию": "Optional",
  "Обязательное": "Required",
  " · правило на день": " · daily rule",
  "Отметь, соблюдено ли правило в выбранный день.": "Mark whether the rule was followed on the selected day.",
  "Отметка выполнения для выбранного дня.": "Completion checkmark for the selected day.",
  "Выбери сегодня или прошедший день.": "Choose today or an earlier day.",
  "Показать": "Show",
  " выключено": " disabled",
  "Изменить отметку": "Edit checkmark",
  " · выключено": " · disabled",
  "Выбери занятие для запуска или название, чтобы изменить его.": "Choose an activity to start, or its title to edit.",
  "идёт": "running",
  "идут": "running",
  "Идёт": "Running",
  ", больше оценки": ", over estimate",
  "Время по стадиям недоступно": "Stage time unavailable",
  "Время этапа недоступно": "Stage time unavailable",
  "Не удалось загрузить время по стадиям": "Could not load stage time",
  "Не удалось загрузить задачи в работе.": "Could not load running tasks.",
  "Загружаем задачи в работе…": "Loading running tasks…",
  "Не удалось обновить список. Показано последнее состояние.": "Could not refresh the list. The last state is shown.",
  "Без названия": "Untitled",
  "Не удалось найти запись о работе. Обнови экран.": "Could not find the work record. Refresh the screen.",
  "Задача снова в работе.": "Task is running again.",
  "Задача остановлена и убрана из «В работе». Время сохранено.": "Task stopped and removed from In progress. Tracked time is preserved.",
  "Запуск отменён. Его время не учтено.": "Run cancelled. Its time is not counted.",
  "Не удалось выполнить действие. Обнови экран и повтори.": "Could not apply action. Refresh the screen and retry.",
  "Пауза, время сохранится": "Pause; tracked time will be preserved",
  "Убрать из «В работе»": "Remove from In progress",
  "Не учитывать этот запуск": "Do not count this run",
  "Шёл сон": "Sleep continued",
  "Продолжение": "Continuation",
  "Продолжится завтра": "Continues tomorrow",
  "Время сна по стадиям не передано источником": "The source did not provide sleep stage time",
  "Событие": "Event",
  "Рутина": "Routine",
  "Запись": "Entry",
  ", без времени": ", untimed",
  "Недельная сетка. Можно прокручивать по горизонтали и вертикали.": "Week grid. Scroll horizontally and vertically.",
  "Сетка дня. Можно прокручивать по вертикали.": "Day grid. Scroll vertically.",
  "стадии сна не переданы": "sleep stages not provided",
  "Нажми свободную ячейку, чтобы создать событие. С клавиатуры: ↑ ↓ выбирают час, Enter открывает форму.": "Click an empty cell to create an event. Keyboard: ↑ ↓ select the hour; Enter opens the form.",
  "На телефоне листай сетку вбок. Полные названия доступны в списке и по нажатию на пункт.": "On a phone, scroll the grid sideways. Full titles are available in the list and by opening an entry.",
  "Сжать длинные события": "Collapse long events",
  "Сжать раскрытые длинные события этого дня": "Collapse expanded long events for this day",
  "К текущему времени": "Go to current time",
  "Эта задача уже недоступна для выполнения. Обнови календарь.": "This task is no longer available. Refresh the calendar.",
  "Состояние задачи изменилось. Обнови календарь перед паузой.": "Task status changed. Refresh the calendar before pausing.",
  "Не удалось завершить задачу после паузы. Её текущий статус обновлён. ": "Could not complete the task after pausing. Its current status was refreshed. ",
  "Попробуй ещё раз.": "Try again.",
  "Неизвестное действие.": "Unknown action.",
  "Данные здоровья": "Health data",
  "Повторение": "Recurring entry",
  "Завершено": "Completed",
  "Не удалось сохранить. Проверь данные и повтори — изменения формы сохранены.": "Could not save. Check the values and retry; the form changes are retained.",
  "Восстановить в этот день": "Restore on this day",
  "Отменить с этого дня": "Cancel from this day",
  "Отменить в этот день": "Cancel on this day",
  "Повторение снова будет запланировано только на этот день.": "The occurrence will be planned again only on this day.",
  "Повторения с выбранного дня перестанут появляться. Предыдущие дни и история сохранятся.": "Occurrences from the selected day will stop appearing. Earlier days and history are preserved.",
  "Остальные дни не изменятся. Это повторение можно будет восстановить из его карточки.": "Other days are unchanged. This occurrence can be restored from its card.",
  "Не удалось изменить повторение. Попробуй ещё раз.": "Could not change the occurrence. Try again.",
  "нет данных о стадиях": "no stage data",
  "нет данных": "no data",
  "Не удалось загрузить цель. Закрой и открой запись повторно.": "Could not load the goal. Close and reopen the entry.",
  "Стадия не выбрана": "No stage selected",
  "Не удалось выполнить действие. Попробуй ещё раз.": "Could not apply action. Try again.",
  "Не удалось загрузить отметку начала дня.": "Could not load the day-start checkmark.",
  "Дата календаря": "Calendar date",
  "Колёсико или клавиши ↑ ↓ — соседний день": "Mouse wheel or ↑ ↓ keys: adjacent day",
  "Учёт времени задачи или рутины. Исполнитель агента автоматически не запускается.": "Track task or routine time. The agent executor does not start automatically.",
  "Что начать": "What to start",
  "Не удалось сменить главную цель. Повтори выбор в целях.": "Could not change the primary goal. Try selecting it again in Goals.",
  "Запланировано на сегодня, {0}.": "Planned for today, {0}.",
  "Задача запланирована на {0}.": "Task planned for {0}.",
  "Время рутины — {0}.": "Routine time: {0}.",
  "По расписанию — {0}.": "Scheduled for {0}.",
  "На паузе. {0}": "Paused. {0}",
  "Рутина · шагов: {0}": "Routine · steps: {0}",
  "Цель: {0}": "Goal: {0}",
  "Этап: {0}": "Stage: {0}",
  "Не удалось обновить рекомендации. Показан последний результат. {0}": "Could not refresh recommendations. The last result is shown. {0}",
  "Не удалось загрузить рекомендации. {0}": "Could not load recommendations. {0}",
  "«{0}» не будет предлагаться в течение часа.": "“{0}” will not be suggested for an hour.",
  "«{0}» — выполнено.": "“{0}” completed.",
  "Перенести {0} {1}?": "Move {0} {1}?",
  "Перенесено на сегодня: {0}.": "Moved to today: {0}.",
  "Перенесено на сегодня: {0} из {1}.": "Moved to today: {0} of {1}.",
  "Убрать дату у {0} {1}?": "Clear date for {0} {1}?",
  "Дата убрана у {0} {1}.": "Date cleared for {0} {1}.",
  "Дата убрана: {0} из {1}.": "Dates cleared: {0} of {1}.",
  "{0} мин · факт {1}": "{0} min · actual {1}",
  "{0} мин": "{0} min",
  "факт {0} мин": "actual {0} min",
  "Оценка: {0} мин": "Estimate: {0} min",
  "Учтено: {0} мин": "Tracked: {0} min",
  "{0}{1}{2} — изменить дату": "{0}{1}{2} — change date",
  "{0}, просрочено. Изменить дату": "{0}, overdue. Change date",
  "Следующая стадия «{0}»: {1}": "Next stage “{0}”: {1}",
  "Сфера: {0}": "Area: {0}",
  "На приёмке · результат v{0}": "Awaiting review · result v{0}",
  "Принято · результат v{0}": "Accepted · result v{0}",
  "По отчёту: {0} / {1} · {2}. Live feed отсутствует.": "Reported: {0} / {1} · {2}. Live feed unavailable.",
  "Источник {0}: {1} · {2}{3}": "Source {0}: {1} · {2}{3}",
  " · результат источника: {0}": " · source result: {0}",
  "Детали: {0}": "Details: {0}",
  "Действия: {0}": "Actions: {0}",
  "Наблюдения без связи с задачами: {0}. Данные источников сохранены.": "Observations not linked to tasks: {0}. Source data is preserved.",
  "Поиск: {0}": "Search: {0}",
  "{0}–{1} из {2}": "{0}–{1} of {2}",
  " и ещё {0}": " and {0} more",
  "{0}Не удалось {1}: {2}. {3} — обнови список и повтори.": "{0}Could not {1}: {2}. {3} — refresh the list and retry.",
  "Этап: {0}.": "Stage: {0}.",
  " · до {0}": " · until {0}",
  "История · {0}": "History · {0}",
  "История отметок за {0}": "Checkmark history for {0}",
  "Ещё {0} на сегодня": "{0} more for today",
  "{0} на сегодня": "{0} for today",
  "{0} без отметки": "{0} unmarked",
  "Отмечено · {0}": "Marked · {0}",
  "{0} включено · {1} выключено": "{0} enabled · {1} disabled",
  "{0} на паузе": "{0} paused",
  "{0} ч {1} мин": "{0} h {1} min",
  "{0} / {1} мин": "{0} / {1} min",
  "{0}. Учтено {1}": "{0}. Tracked {1}",
  "{0} из {1} мин{2}": "{0} of {1} min{2}",
  "Учтено на этапе {0}": "Tracked on stage {0}",
  "Отменить запуск: {0}": "Cancel run: {0}",
  "Время этого запуска{0} не сохранится.": "Time for this run{0} will not be preserved.",
  " ({0} мин)": " ({0} min)",
  " (+{0} д.)": " (+{0} d)",
  "{0}, {1}, {2}, {3}. Открыть подробности": "{0}, {1}, {2}, {3}. Open details",
  "Учтён в дне пробуждения: {0}": "Counted on the wake-up day: {0}",
  "За ночь: {0} ч {1} мин": "Overnight: {0} h {1} min",
  "{0}, без времени: {1}": "{0}, untimed: {1}",
  "Показать · {0}": "Show · {0}",
  "{0}, пунктов: {1}": "{0}, entries: {1}",
  "{0}. Начало дня: {1}": "{0}. Day start: {1}",
  "; ещё {0}": "; {0} more",
  "Выбранный день · {0}": "Selected day · {0}",
  "Шаги: {0}": "Steps: {0}",
  ". Шагов: {0}": ". Steps: {0}",
  "Новое событие: {0}, {1}": "New event: {0}, {1}",
  "{0} · Новое событие": "{0} · New event",
  "Сжатый интервал {0}–{1}: {2}. Развернуть.": "Collapsed interval {0}–{1}: {2}. Expand.",
  "{0} ч": "{0} h",
  "Шёл сон · Учтён {0} · Развернуть": "Sleep continued · Counted on {0} · Expand",
  "{0}–{1} · {2} · {3} · Развернуть": "{0}–{1} · {2} · {3} · Expand",
  "Источник: {0}. Период сна: {1} мин. Во сне: {2}.": "Source: {0}. Sleep period: {1} min. Asleep: {2}.",
  "Источник: {0}. Период прогулки: {1} мин.": "Source: {0}. Walk period: {1} min.",
  "Источник: Health Connect (все доступные источники). Шагов за день: {0}. Итог не имеет времени начала.": "Source: Health Connect (all available sources). Daily steps: {0}. The total has no start time.",
  "Учтено времени: {0} мин": "Tracked time: {0} min",
  "Вернуться: {0}": "Return: {0}",
  "Завершить день": "End day",
  "План на завтра": "Plan for tomorrow",
  "Итоги дней": "Day summaries",
  "Итог дня": "Day summary",
  "Повторить сохранение": "Retry save",
  "Отбросить повреждённый запрос": "Discard corrupted request",
  "Хранилище запроса дня недоступно. Сохранение заблокировано.": "Day request storage is unavailable. Saving is blocked.",
  "Сохранённый запрос повреждён. Его нельзя повторить. Отбросьте его для нового предпросмотра; подтверждённые итоги остаются в истории.": "The saved request is corrupted and cannot be retried. Discard it for a new preview; confirmed summaries remain in history.",
  "Сохранение не подтверждено. Повтори тот же запрос.": "Saving is unconfirmed. Retry the same request.",
  "День закрыт. Таймеры не возобновляются автоматически.": "The day is closed. Timers do not resume automatically.",
  "План на сегодня": "Plan for today",
  "Состояние дня недоступно. Данные не изменены.": "Day state is unavailable. Data is unchanged.",
  "Не удалось сохранить запрос для повторной попытки. Данные не изменены.": "Could not save the request for retry. Data is unchanged.",
  "Не удалось сохранить запрос для повторной попытки.": "Could not save the request for retry.",
  "Предпросмотр устарел или данные изменились. Закрой окно и перечитай состояние.": "The preview is stale or data has changed. Close the dialog and reload the state.",
  "Сохранение не подтверждено. Повтори тот же запрос; новое действие пока недоступно.": "Saving is unconfirmed. Retry the same request; a new action is unavailable for now.",
  "Предпросмотр недоступен. Данные не изменены.": "Preview is unavailable. Data is unchanged.",
  "Открыть день снова": "Reopen day",
  "Сохранить план": "Save plan",
  "План на {date}. Сроки задач сохраняются.": "Plan for {date}. Task deadlines stay unchanged.",
  " · срок ": " · due ",
  "Незавершённых задач нет. Можно сохранить пустой план.": "No unfinished tasks. You can save an empty plan.",
  "Закрыт: ": "Closed: ",
  "Повторное открытие сохраняет итог и не запускает таймеры.": "Reopening preserves the summary and does not start timers.",
  "Будут поставлены на паузу человеческие таймеры:": "These human timers will be paused:",
  "Работающих человеческих таймеров нет.": "No human timers are running.",
  "Задачи остаются незавершёнными. Работа ИИ не меняется.": "Tasks remain unfinished. AI work is unchanged.",
  " · закрыт": " · closed",
  " · открыт": " · open",
  "Не удалось сохранить повреждённый запрос отдельно. Он не удалён.": "Could not save the corrupted request separately. It has not been deleted.",

  "Открыть текущее": "Open current activity",
  "Отметить выполненным": "Mark completed",
  "Проверить задачу": "Review task",
  "Не предлагать час": "Do not suggest for an hour",
  "Без времени": "Untimed",
  "Время": "Time",
  "Детали": "Details",
  "Не выбран": "Not selected",
  "Оставить": "Keep",
  "Открыть ожидание": "Open waiting task",
  "Всего / оценка": "Total / estimate",
  "Затрачено": "Time spent",
  "Период календаря": "Calendar period",
  "Сменить главную цель": "Change primary goal",
  "Что показать": "What to show",
  "Изменить дату": "Change date",
  "Восстановить повторение": "Restore occurrence",
  "Отменить повторение": "Cancel occurrence",

  "По дате": "By date",
  "По цели": "By goal",
  "Активные": "Active",
  "На приёмке": "Awaiting review",
  "ИИ: running по отчётам": "AI: running in reports",
  "Группировать задачи": "Group tasks",
  "Какие задачи показать": "Tasks to show",
  "Фильтр по цели": "Filter by goal",
  "Сфера личных задач": "Personal task area",
  "Источник задачи": "Task source",
  "Проект": "Project",
  "Тег": "Tag",
  "Пауза": "Pause",
  "Назначить дату": "Set date",
  "Завершена": "Completed",
  "Запланированных пунктов нет.": "No items planned.",
  "Дневная сетка": "Day grid",
  "Сетка недели": "Week grid",
  "Сегодня нет записей.": "No entries today.",
  "Расписание": "Schedule",
  "Сохранение языка не подтверждено.": "Language save was not confirmed.",
  "Не удалось обновить начало дня. Повтори загрузку.": "Could not refresh day start. Retry loading.",
  "Не удалось сохранить начало дня. Повтори попытку.": "Could not save day start. Try again.",
  "Не удалось прочитать начало дня.": "Could not read day start.",

  "Язык интерфейса": "Interface language",
  "Русский": "Русский",
  "Не удалось прочитать настройки языка. Используется русский.": "Could not read language settings. Russian is being used.",
  "Открыть меню": "Open menu",
  "Дашборд": "Dashboard",
  "Таблица": "Table",
  "Цели": "Goals",
  "Заметки": "Notes",
  "События и расписание": "Events and schedule",
  "Начать": "Start",
  "Создать задачу, событие, цель, заметку, желание или рутину": "Create a task, event, goal, note, wish or routine",
  "Начать учёт времени задачи или рутины": "Start timing a task or routine",
  "Всё": "All",
  "Все": "All",
  "Сейчас": "Now",
  "Что сделать сейчас": "What to do now",
  "Выбрать другое": "Choose another",
  "К рекомендации": "Back to recommendation",
  "Выбрать дело": "Choose an activity",
  "Что выбрать": "What to choose",
  "Настроить рекомендации на сегодня": "Configure today's recommendations",
  "Начать день": "Start day",
  "✓ День начат · ": "✓ Day started · ",
  "Повторить": "Retry",
  "Просрочено": "Overdue",
  "Скоро": "Soon",
  "Без даты": "Undated",
  "Завершённые": "Completed",
  "Работа": "Work",
  "Личное": "Personal",
  "Дом": "Home",
  "Здоровье": "Health",
  "Развитие": "Development",
  "Без сферы": "No area",
  "Без цели": "No goal",
  "Любая цель": "Any goal",
  "Найти задачу": "Find a task",
  "Фильтры и группировка": "Filters and grouping",
  "Сбросить фильтры": "Reset filters",
  "Рабочие или личные задачи": "Work or personal tasks",
  "Найти рутину": "Find a routine",
  "Найти занятие или правило": "Find an activity or rule",
  "Рутин пока нет": "No routines yet",
  "Здесь будут повторяющиеся дела и ветки шагов.": "Recurring activities and branching steps will appear here.",
  "Создай их через общий «Создать» → «Рутина».": "Use Create → Routine to add one.",
  "Ничего не найдено. Попробуй другое название.": "Nothing found. Try another name.",
  "Добавить рутину": "Add routine",
  "Добавь повторяющееся дело, занятие или цепочку шагов.": "Add a recurring activity or a sequence of steps.",
  "История": "History",
  "Дневные отметки": "Daily checkmarks",
  "День учёта": "Tracking day",
  "Вернуться к сегодня": "Back to today",
  "Все задачи": "All tasks",
  "Дела": "Activities",
  "Правило на день": "Daily rule",
  "Каждый день": "Every day",
  "С учётом времени": "With timing",
  "Без таймера": "Without a timer",
  "Правила": "Rules",
  "Отмечено": "Marked",
  "Отметить": "Mark",
  "Отменить отметку": "Undo mark",
  "Ещё не отмечено": "Not marked yet",
  "Соблюдено": "Followed",
  "Не соблюдено": "Not followed",
  "✓ Выполнено": "✓ Completed",
  "Просмотреть": "View",
  "Изменить рутину": "Edit routine",
  "Изменить": "Edit",
  "Отменить": "Cancel",
  "Продолжить": "Continue",
  "Открыть": "Open",
  "Загружаем рутины…": "Loading routines…",
  "Загружаем задачи…": "Loading tasks…",
  "Загружаем цели…": "Loading goals…",
  "Загружаем цель…": "Loading goal…",
  "Загружаем расписание…": "Loading schedule…",
  "Загружаем учтённое время…": "Loading tracked time…",
  "Не удалось загрузить цели. Сохранённые цели остаются на месте.": "Could not load goals. Stored goals are preserved.",
  "Не удалось загрузить расписание. Это не означает, что календарь пуст.": "Could not load the schedule. This does not mean the calendar is empty.",
  "Учтённое время сейчас недоступно.": "Tracked time is currently unavailable.",
  "Главная": "Primary",
  "Главная цель": "Primary goal",
  "Подцель": "Subgoal",
  "Желания": "Wishes",
  "Цель": "Goal",
  "Выбрать цель": "Choose a goal",
  "Выбрать": "Choose",
  "Все цели": "All goals",
  "Название цели": "Goal title",
  "Найти цель": "Find a goal",
  "Верхний уровень": "Top level",
  "Сделать главной": "Make primary",
  "Добавить задачу": "Add task",
  "Достигнута": "Achieved",
  "Редактировать": "Edit",
  "Редактировать цель": "Edit goal",
  "Родительская цель": "Parent goal",
  "Желаемый результат": "Desired result",
  "Что хочешь получить?": "What would you like to achieve?",
  "Что должно измениться?": "What should change?",
  "Критерии — по одному на строку": "Criteria, one per line",
  "Срок · необязательно": "Deadline · optional",
  "Как учитывать": "How to track",
  "Числовой прогресс": "Numeric progress",
  "Долгосрочная цель": "Long-term goal",
  "Ежедневная норма": "Daily target",
  "Текущий прогресс · необязательно": "Current progress · optional",
  "Целевое значение": "Target value",
  "Единица измерения": "Unit",
  "Можно сохранить идею без срока и без готового плана.": "You can save an idea without a deadline or a complete plan.",
  "Начни с того, что важно тебе": "Start with what matters to you",
  "Выбираем главную цель…": "Selecting primary goal…",
  "Удалить": "Delete",
  "Удалить цель?": "Delete goal?",
  "Связанные записи": "Linked records",
  "Пока нет связанных записей. Цель можно сохранить без задач.": "No linked records yet. A goal can be saved without tasks.",
  "Текущая задача": "Current task",
  "Текущие задачи": "Current tasks",
  "Задача на сейчас": "Task for now",
  "По рекомендации": "Recommended",
  "Все подходящие задачи": "All suitable tasks",
  "Дальше": "Next",
  "Навык на сейчас": "Skill for now",
  "План цели": "Goal plan",
  "Этапы": "Stages",
  "Этап:": "Stage:",
  "Навыки": "Skills",
  "Навыки этапа (необязательно)": "Stage skills (optional)",
  "Вся цель": "Whole goal",
  "Все темы": "All topics",
  "Добавить этап": "Add stage",
  "Добавить навык": "Add skill",
  "Навык": "Skill",
  "Тема": "Topic",
  "Группа": "Group",
  "Хард": "Hard",
  "Софт": "Soft",
  "Название этапа": "Stage name",
  "Название навыка": "Skill name",
  "Какой этап сейчас": "Current stage",
  "Критерии готовности": "Completion criteria",
  "Промежуточный результат": "Intermediate result",
  "Практика": "Practice",
  "Подтверждение навыка": "Skill evidence",
  "Какой результат подтверждает навык": "What result demonstrates the skill",
  "Срок (необязательно)": "Deadline (optional)",
  "Найти навык или тему": "Find a skill or topic",
  "Найти навык, тему или описание": "Find a skill, topic or description",
  "Ничего не найдено": "Nothing found",
  "Очистить выбор": "Clear selection",
  "Сделать текущим": "Make current",
  "Возобновить": "Resume",
  "Завершить": "Finish",
  "Задача": "Task",
  "Исключить": "Exclude",
  "Ориентир": "Target",
  "В выбранном этапе пока нет навыков. Добавь навык по желанию.": "No skills in the selected stage yet. Add one if needed.",
  "Раздели цель на ближайший результат.": "Break the goal into the next result.",
  "Добавь ближайший промежуточный результат. Навык можно привязать позже.": "Add the next intermediate result. A skill can be linked later.",
  "Сначала выбери тему. Поиск сузит список тем.": "Choose a topic first. Search narrows the topic list.",
  "Связанные задачи и подтверждения навыков сохранятся.": "Linked tasks and skill evidence will be preserved.",
  "Запустить": "Start",
  "Запустить ещё": "Start another",
  "Ничего не запущено": "Nothing running",
  "Остановить": "Stop",
  "Отменить запуск": "Cancel run",
  "Запущено и на паузе": "Running and paused",
  "Запущено и на паузе сегодня": "Running and paused today",
  "Идёт сейчас": "Running now",
  "Что начнём?": "What shall we start?",
  "Вернуться к целям": "Back to goals",
  "Завершить задачу": "Finish task",
  "Связать с целью": "Link to goal",
  "Перенести на сегодня": "Move to today",
  "Убрать дату": "Clear date",
  "Какие повторения": "Which occurrences",
  "Только в этот день": "Only this day",
  "С этого дня и дальше": "From this day onward",
  "Загружаем задачи и дела…": "Loading tasks and activities…",
  "Рекомендации выключены.": "Recommendations are disabled.",
  "Подходящей задачи или дела сейчас нет.": "No suitable task or activity right now.",
  "Настроить": "Configure",
  "Свернуть": "Collapse",
  "✓ Завершённые": "✓ Completed",
  "↷ Пропущенные": "↷ Skipped",
  "Пн": "Mon",
  "Вт": "Tue",
  "Ср": "Wed",
  "Чт": "Thu",
  "Пт": "Fri",
  "Сб": "Sat",
  "Вс": "Sun",

  "Запланирован": "Planned",
  "В работе": "In progress",
  "Жду ответа": "Waiting for a response",
  "Готов": "Done",
  "Ближайший шаг задачи": "Next task step",
  "Указать ближайший шаг": "Set next step",
  "Шаги и результат": "Steps and result",
  "Отмечай ход работы вручную. Шаги не меняют этап или таймер задачи.": "Track progress manually. Steps do not change the task stage or timer.",
  "Шаги задачи": "Task steps",
  "Следующий шаг": "Next step",
  "Добавить шаг": "Add step",
  "Результат задачи": "Task result",
  "Сохранить результат": "Save result",
  "Отменить ввод": "Discard input",
  "Повторить чтение": "Read again",
  "Обновить состояние": "Refresh status",
  "Ближайший шаг ещё не указан.": "No next step has been set.",
  "Незавершённые шаги ждут ответа.": "Unfinished steps are waiting for a response.",
  "Выбрать другой шаг": "Choose another step",
  "Шаги и результат · шаги не указаны": "Steps and result · no steps set",
  "Статус шага сохранён.": "Step status saved.",
  "Ожидание": "Waiting",
  "Завершён": "Completed",
  "Ошибка": "Error",
  "Отменён": "Cancelled",
  "неизвестно": "unknown",
  "Статус внешнего исполнителя недоступен. Расходы неизвестны.": "External executor status unavailable. Usage is unknown.",
  "Внешний исполнитель не связан. Автоматическое выполнение не запускалось.": "No external executor is linked. Automatic execution has not started.",
  "Читаем ближайший шаг…": "Reading the next step…",
  "Загрузка шагов…": "Loading steps…",
  "Импортированный реестр недоступен. Статус исполнения неизвестен.": "Imported registry unavailable. Execution status unknown.",
  "Шаги и результат · данные недоступны": "Steps and result · data unavailable",
  "Ближайший шаг не обновлён. Ниже — последнее подтверждённое состояние.": "The next step was not refreshed. The last confirmed state is shown below.",
  "Ближайший шаг неизвестен: не удалось прочитать данные.": "Next step unknown: could not read the data.",
  "Не удалось прочитать шаги. Формат может быть новее этой версии; данные сохранены без изменений. Сохранение недоступно.": "Could not read steps. The format may be newer than this version; stored data is unchanged. Saving is unavailable.",
  "Сохранение…": "Saving…",
  "Не удалось сохранить. Данные не подтверждены; перечитай состояние и повтори.": "Could not save. Data is unconfirmed; read the status again and retry.",
  "Шаг сохранён.": "Step saved.",
  "Результат сохранён.": "Result saved.",
  "Несохранённый ввод отменён.": "Unsaved input discarded.",
  "Дождись сохранения шагов.": "Wait for the steps to finish saving.",
  "Сохрани шаг или результат перед закрытием.": "Save the step or result before closing.",
  "Выбор следующего действия": "Next action selection",
  "Настройки Cicada": "Cicada settings",
  "Сохранить": "Save",
  "Сохранить календарь": "Save calendar",
  "Разделы настроек": "Settings sections",
  "Отмена": "Cancel",
  "Отмена и закрыть настройки": "Cancel and close settings",
  "Повторить загрузку": "Retry loading",
  "Загружаем настройки выбора…": "Loading selection settings…",
  "Загружаем настройки календаря…": "Loading calendar settings…",
  "Подтверждение закрытия с несохранёнными изменениями": "Confirm closing with unsaved changes",
  "Есть несохранённые изменения.": "There are unsaved changes.",
  "Продолжить редактирование": "Continue editing",
  "Закрыть без сохранения": "Close without saving",
  "Закрыть": "Close",
  "Первый день недели": "First day of the week",
  "Вид при запуске": "Startup view",
  "Плотность интерфейса": "Interface density",
  "Здоровье: сон, прогулки и шаги": "Health: sleep, walks and steps",
  "В этой сборке интеграция Jira недоступна. Здесь нет данных о подключении или импорте. Подключение на другом устройстве нужно проверить на том устройстве.": "Jira integration is unavailable in this build. There is no connection or import data here. A connection on another device must be checked on that device.",
  "Настройки календаря сохранены. Черновик этапов ещё не сохранён — сохрани его во вкладке «Этапы задач» или закрой настройки с отменой.": "Calendar settings saved. The stage draft is not saved yet: save it in Task stages or close settings and discard it.",
  "Настройки календаря сохранены. Изменения подключения ещё не сохранены.": "Calendar settings saved. Connection changes are not saved yet.",
  "Ошибка сохранения.": "Save error.",
  "настроек выбора": "selection settings",
  "календаря": "calendar",
  "Процессы задач": "Task processes",
  "Стадии для задач с процессом. Переименование не меняет задачи. Если удалить стадию, её задачи покажут «Стадия удалена», пока ты не выберешь другую.": "Stages for tasks with a process. Renaming does not change tasks. Deleting a stage makes its tasks show Deleted stage until you select another one.",
  "Загружаем процессы…": "Loading processes…",
  "＋ Новый процесс": "＋ New process",
  "Сохранить процессы": "Save processes",
  "Отменить изменения": "Discard changes",
  "Встроенный процесс": "Built-in process",
  "Процесс": "Process",
  "Новый процесс": "New process",
  "Например, Ремонт": "For example, Renovation",
  "Название процесса": "Process name",
  "процесс без названия": "untitled process",
  "Название стадии": "Stage name",
  "процесс": "process",
  "＋ Стадия": "＋ Stage",
  "без названия": "untitled",
  "Убрать": "Remove",
  "Один процесс": "One process",
  "Не удалось загрузить процессы.": "Could not load processes.",
  "Сохраняем процессы…": "Saving processes…",
  "Процессы сохранены.": "Processes saved.",
  "Не удалось сохранить процессы. Изменения остались в форме.": "Could not save processes. Changes remain in the form.",
  "Изменения отменены.": "Changes discarded.",
  "Синхронизация": "Synchronization",
  "Загружаем состояние…": "Loading status…",
  "Состояние этого устройства. Другое устройство получит изменения после своего подключения.": "Status of this device. Other devices receive changes after connecting.",
  "Код подключения": "Connection code",
  "Вставь код подключения устройства": "Paste the device connection code",
  "Код подключения устройства": "Device connection code",
  "Показать код": "Show code",
  "Скрыть код": "Hide code",
  "Синхронизация включена": "Synchronization enabled",
  "Сохранить подключение": "Save connection",
  "Синхронизировать сейчас": "Sync now",
  "Разобрать сохранённые версии": "Review saved versions",
  "Нет доступа к сохранённому ключу синхронизации. Локальные данные сохранены. После восстановления доступа к хранилищу ключей перезапусти Cicada.": "The stored sync key is inaccessible. Local data is preserved. Restart Cicada after restoring access to the key store.",
  "Подключить устройство": "Connect device",
  "Состояние синхронизации недоступно.": "Sync status unavailable.",
  "Синхронизация приостановлена: ключ подключения недоступен.": "Sync paused: connection key unavailable.",
  "Устройство ещё не подключено.": "This device is not connected yet.",
  "Синхронизация выключена.": "Synchronization disabled.",
  "Идёт обмен изменениями…": "Exchanging changes…",
  "Нет сети. Изменения остаются на этом устройстве.": "Offline. Changes remain on this device.",
  "Последний обмен не завершён. Изменения ожидают повторной попытки.": "The last exchange did not finish. Changes are awaiting a retry.",
  "Подключение включено.": "Connection enabled.",
  "Сеть недоступна. Повторим обмен после подключения.": "Network unavailable. The exchange will retry after connecting.",
  "Код подключения больше не принят сервером.": "The server no longer accepts the connection code.",
  "Устройство не имеет доступа к обмену.": "This device has no access to the exchange.",
  "Для продолжения синхронизации обнови Cicada на этом устройстве.": "Update Cicada on this device to continue syncing.",
  "Сервер просит повторить попытку позже.": "The server asks to retry later.",
  "На сервере не хватает места для изменений.": "The server has insufficient space for changes.",
  "Подключение изменилось. Повтори обмен с текущим подключением.": "The connection changed. Retry the exchange using the current connection.",
  "Проверь код подключения.": "Check the connection code.",
  "Не удалось создать резервную копию перед включением синхронизации.": "Could not create a backup before enabling sync.",
  "Не удалось включить фоновую синхронизацию. Повтори включение синхронизации.": "Could not enable background sync. Try enabling sync again.",
  "Последний обмен завершился ошибкой. Локальные изменения сохранены.": "The last exchange failed. Local changes are preserved.",
  "Успешный обмен ещё не подтверждён.": "A successful exchange has not been confirmed yet.",
  "Не удалось прочитать состояние синхронизации.": "Could not read sync status.",
  "Код подключения должен содержать JSON. Проверь, что он скопирован целиком.": "The connection code must contain JSON. Check that you copied it in full.",
  "Вставь код подключения этого устройства.": "Paste the connection code for this device.",
  "Не удалось сохранить подключение. Проверь код и повтори попытку.": "Could not save the connection. Check the code and try again.",
  "Не удалось завершить обмен. Локальные изменения сохранены; повтори попытку при доступной сети.": "Could not finish the exchange. Local changes are preserved; retry when online.",
  "Сравни названия и фрагменты полей перед выбором. Выбор текущей версии закрывает только эту запись на этом устройстве.": "Compare titles and field excerpts before choosing. Keeping the current version closes only this entry on this device.",
  "Обновить список": "Refresh list",
  "К списку": "Back to list",
  "Назад": "Previous",
  "Далее": "Next",
  "Запись уже удалена. Сохранённая версия не может отменить удаление.": "The record is already deleted. A saved version cannot undo deletion.",
  "Версии относятся к разным записям. Замена недоступна.": "The versions belong to different records. Replacement is unavailable.",
  "Связанная задача или цель ещё не получена. Обнови список после синхронизации.": "The linked task or goal has not arrived yet. Refresh the list after syncing.",
  "У записи есть связанные задачи или цели. Сначала обнови их связи.": "The record has linked tasks or goals. Update those links first.",
  "Такая связь создаст замкнутую цепочку целей. Выбери другую родительскую цель.": "This link would create a goal cycle. Choose another parent goal.",
  "Выбранная родительская цель не поддерживает эту связь.": "The selected parent goal does not support this link.",
  "Сначала приостанови текущую задачу, затем обнови список.": "Pause the current task first, then refresh the list.",
  "Сохранённая версия содержит старый запуск задачи. Автоматическая замена недоступна.": "The saved version contains an old task run. Automatic replacement is unavailable.",
  "Формат записи пока не поддерживается. Доступен только просмотр.": "The record format is not supported yet. Only viewing is available.",
  "Записи нет на этом устройстве.": "The record is absent on this device.",
  "Запись удалена.": "The record is deleted.",
  "Эту версию нельзя безопасно отобразить.": "This version cannot be displayed safely.",
  "Настройки или связи записи.": "Record settings or links.",
  "На этом устройстве": "On this device",
  "Входящая версия": "Incoming version",
  "Сохранённая версия": "Saved version",
  "Эту версию пока нельзя безопасно применить. Обнови список после синхронизации.": "This version cannot be applied safely yet. Refresh the list after syncing.",
  "Оставить текущее": "Keep current",
  "Использовать эту версию": "Use this version",
  "Загружаем версии…": "Loading versions…",
  "Неразобранных версий нет.": "No versions remain to review.",
  "Не удалось загрузить версии. Попробуй ещё раз.": "Could not load versions. Try again.",
  "Сохраняем выбор…": "Saving your choice…",
  "Выбранная версия сохранена. Изменение ожидает синхронизации.": "Selected version saved. The change is awaiting sync.",
  "Текущая версия сохранена.": "Current version saved.",
  "Запись изменилась, пока ты сравнивал версии. Обнови список и выбери заново.": "The record changed while you compared versions. Refresh the list and choose again.",
  "Не удалось применить выбор. Записи сохранены; обнови список.": "Could not apply the choice. Records are preserved; refresh the list.",
  "Файлы и источники": "Files and sources",
  "Выбери папку и проверь структуру перед сохранением. Данные не читаются, задачи не перезаписываются. Видимость и размещение применяются к разделам источников в личном Cicada. Автоматического обновления нет.": "Choose a folder and check its structure before saving. Data is not read and tasks are not overwritten. Visibility and placement apply to source sections in personal Cicada. There is no automatic refresh.",
  "Сохранить источники": "Save sources",
  "Абсолютный путь к папке": "Absolute folder path",
  "Папка не проверена.": "Folder not checked.",
  "Путь изменён. Проверь папку перед сохранением.": "Path changed. Check the folder before saving.",
  "Выбор папки недоступен. Вставь абсолютный путь и проверь его.": "Folder picker unavailable. Paste an absolute path and check it.",
  "Показывать раздел": "Show section",
  "Предпочитать локальный private Git": "Prefer local private Git",
  "Размещение": "Placement",
  "Tasks • перед обычными задачами": "Tasks • before regular tasks",
  "Projects • после источников задач": "Projects • after task sources",
  "Проверка не удалась: требуется существующая локальная папка без ссылок и ожидаемые типы. Содержимое не читалось.": "Check failed: an existing local folder without links and with expected types is required. Contents were not read.",
  "Настройки сохранены. Разделы источников обновлены. Файлы не импортированы; режим ручной.": "Settings saved. Source sections updated. Files were not imported; mode is manual.",
  "Сохранение не подтверждено. Проверь абсолютные пути или открой настройки заново.": "Saving is unconfirmed. Check absolute paths or reopen settings.",
  "Настройки загружены. Источники не проверены; автоматического обновления нет.": "Settings loaded. Sources have not been checked; there is no automatic refresh.",
  "Источники не настроены. Можно пропустить и вернуться позже.": "Sources are not configured. You can skip and return later.",
  "Настройки недоступны; сохранение заблокировано.": "Settings unavailable; saving is blocked.",
  "Подключить папки данных?": "Connect data folders?",
  "Можно настроить локальные источники сейчас или пропустить. Задачи доступны без подключения.": "You can configure local sources now or skip. Tasks are available without a connection.",
  "Настроить источники": "Configure sources",
  "Пропустить": "Skip",
  "Не удалось сохранить выбор. Попробуй снова.": "Could not save your choice. Try again.",
  "есть": "present",
  "нет": "absent",
  "Импортированный рабочий реестр": "Imported work registry",
  "Снимки engineering-задач, опубликованные родителем. Это не live-поток и не запуск исполнителя.": "Engineering task snapshots published by the parent. This is not a live stream or executor launch.",
  "JSON снимка": "Snapshot JSON",
  "Предварительный просмотр": "Preview",
  "Импортировать просмотренный снимок": "Import previewed snapshot",
  "Импортированные работы": "Imported work",
  "Операция": "Operation",
  "Ожидает": "Waiting for",
  "Результат": "Result",
  "Предпросмотр. Данные ещё не сохранены.": "Preview. Data has not been saved yet.",
  "Снимок некорректен или содержит неподдерживаемые поля. Ничего не сохранено.": "The snapshot is invalid or contains unsupported fields. Nothing was saved.",
  "Снимок сохранён. Задачи и ручные шаги не изменены.": "Snapshot saved. Tasks and manual steps are unchanged.",
  "Этот снимок уже сохранён.": "This snapshot is already saved.",
  "Импорт не подтверждён. Проверь sequence или перечитай состояние.": "Import unconfirmed. Check sequence or read the status again.",
  "Сохранённый реестр недоступен. Импорт не выполнялся.": "Stored registry unavailable. No import was performed.",
  "Импорт личных задач из файла": "Import personal tasks from a file",
  "Предпросмотр ничего не записывает. Импорт создаёт резервную копию. Архив — только по явно указанным ID личных шаблонов.": "Preview writes nothing. Import creates a backup. Archiving applies only to explicitly listed personal template IDs.",
  "Файл личных задач": "Personal tasks file",
  "Создать backup и импортировать": "Create backup and import",
  "Я сохранил экспорт и план восстановления": "I saved the export and recovery plan",
  "Сохранить экспорт и план восстановления": "Save export and recovery plan",
  "Сохранение и проверка экспорта не подтверждены.": "Export saving and verification are unconfirmed.",
  "Выбери JSON до 64 КБ.": "Choose a JSON file up to 64 KB.",
  "Создать": "Create",
  "Обновить": "Update",
  "Уже записано": "Already stored",
  "Описание и метки": "Description and tags",
  "без проектов": "no projects",
  "Проверь список, сохрани экспорт и подтверди его сохранение.": "Check the list, save the export and confirm that you saved it.",
  "Все задачи уже записаны.": "All tasks are already stored.",
  "Задачи записаны и перечитаны. Итоговый отчёт содержит путь backup.": "Tasks saved and read back. The final report contains the backup path.",
  " Не удалось сохранить отчёт. Повтори его сохранение.": " Could not save the report. Try saving it again.",
  "Сейчас: ": "Now: ",
  " · ещё в работе: ": " · more running: ",
  "Ближайший шаг: ": "Next step: ",
  "Все сохранённые шаги выполнены: ": "All saved steps completed: ",
  "Ждём ответа: ": "Waiting for a response: ",
  " · ещё ожидают: ": " · more waiting: ",
  "Шаги и результат · выполнено ": "Steps and result · completed ",
  " из ": " of ",
  "Статус шага: ": "Step status: ",
  "Последний импортированный отчёт ": "Latest imported report ",
  "Токены: ": "Tokens: ",
  ". Стоимость не сообщена.": ". Cost not reported.",
  "Попытка ": "Attempt ",
  " подготовлена. Отчёта о выполнении нет. Расходы неизвестны.": " prepared. No execution report. Usage unknown.",
  "Последнее событие ": "Latest event ",
  "Импортированный отчёт — ": "Imported report — ",
  ". Последнее наблюдение: ": ". Last observed: ",
  ". Источник отчёта: ": ". Report source: ",
  ". Основание: ": ". Evidence: ",
  " • операция: ": " • operation: ",
  " • ожидание: ": " • waiting for: ",
  " • результат: ": " • result: ",
  "Рекомендация в «Сегодня»": "Recommendation in Today",
  "Учитываем текущую работу, даты и важность задач, время суток и отметки рутин. Запуск — только по твоему нажатию.": "Uses current work, task dates and importance, time of day and routine check-ins. Starts only when you click.",
  "Предлагать, чем заняться": "Suggest what to do",
  "Задачи": "Tasks",
  "Рутины": "Routines",
  "Отметки рутин": "Routine check-ins",
  "Раскрывать отмеченные рутины": "Expand checked routines",
  "Рутины и правила": "Routines and rules",
  "Вид календаря": "Calendar view",
  "Эти изменения сохраняются кнопкой «Сохранить календарь».": "Save these changes with Save calendar.",
  "Стадии: ": "Stages: ",
  "стадия ": "stage ",
  "Стадия ": "Stage ",
  "Выше: ": "Move up: ",
  "Ниже: ": "Move down: ",
  "Удалить стадию: ": "Delete stage: ",
  "Добавить стадию: ": "Add stage: ",
  "Убрать новый процесс: ": "Remove new process: ",
  "Стадия «": "Stage “",
  "» теперь ": "” is now at position ",
  "-я.": ".",
  "» будет удалена после сохранения.": "” will be deleted after saving.",
  "Процессов: ": "Processes: ",
  "Ожидают отправки: ": "Pending to send: ",
  " · Конфликты: ": " · Conflicts: ",
  "Последний успешный обмен: ": "Last successful exchange: ",
  "Изменено: ": "Updated: ",
  "Сохранено версий: ": "Saved versions: ",
  "Выбрать папку ": "Choose folder ",
  "Проверить папку ": "Check folder ",
  "Проверено ": "Checked ",
  ". Только метаданные; содержимое не импортировано.": ". Metadata only; contents were not imported.",
  "Источник: ": "Source: ",
  " • опубликован ": " • published ",
  " • снимок ": " • snapshot ",
  " • подзадача ": " • subtask ",
  " • источник: ": " • source: ",
  "Экспорт сохранён и проверен: ": "Export saved and verified: ",
  "Не удалось сохранить экспорт. ": "Could not save the export. ",
  " Повтори сохранение; импорт пока недоступен.": " Try saving again; import is unavailable until then.",
  "Было: ": "Before: ",
  "Станет: ": "After: ",
  "Личная задача. Проекты: ": "Personal task. Projects: ",
  "В архив: ": "Archive: ",
  " (версия ": " (version ",
  "Понедельник": "Monday",
  "Воскресенье": "Sunday",
  "Месяц": "Month",
  "Неделя": "Week",
  "День": "Day",
  "Обычная": "Comfortable",
  "Компактная": "Compact",
  "Сегодня": "Today",
  "Календарь": "Calendar",
  "Этапы задач": "Task stages",
  "Подключения": "Connections",
  "О приложении": "About",
  "Не удалось загрузить настройки календаря.": "Could not load calendar settings.",
  "Ожидает безопасного применения": "Awaiting safe application",
  "Сохранена альтернативная версия": "Alternative version saved",
  "Данные и источники": "Data and sources",
  "Выбери папку и проверь структуру перед сохранением. Файлы не читаются, данные не переносятся. Видимость и размещение применяются к разделам источников в области задач. Автоматического обмена нет.": "Choose a folder and check its structure before saving. Files are not read and data is not transferred. Visibility and placement apply to source sections in Tasks. There is no automatic exchange.",
  "Предлагаемая структура:\n<app>-data/manifest.json\n<app>-data/projects/\n<app>-data/tasks/\n<app>-data/runs/\nCredentials и sessions хранятся отдельно.\nGit local/private — предпочтение, репозиторий не создан.": "Suggested structure:\n<app>-data/manifest.json\n<app>-data/projects/\n<app>-data/tasks/\n<app>-data/runs/\nCredentials and sessions are stored separately.\nLocal/private Git is a preference; no repository was created.",
  "Проверка не удалась: требуется существующая локальная папка без ссылок и неверных типов. Содержимое не читалось.": "Check failed: an existing local folder without links or invalid types is required. Contents were not read.",
  "Выбор папки недоступен. Введи абсолютный путь и проверь его.": "Folder picker unavailable. Enter an absolute path and check it.",
  "Tasks • перед локальными задачами": "Tasks • before local tasks",
  "Projects • после локальных задач": "Projects • after local tasks",
  "Не удалось сохранить выбор. Повтори позже.": "Could not save your choice. Try again later.",
  "Проверка результата ИИ": "AI result review",
  "Замечание для доработки": "Rework comment",
  "История решений": "Decision history",
  "Принять": "Accept",
  "Передан на приёмку": "Submitted for review",
  "Принят": "Accepted",
  "На доработку": "Requested rework",
  "Доработка начата": "Rework started",
  "Изменение": "Change",
  "Результат ИИ": "AI result",
  "Доработать": "Request rework",
  "Обновить результат": "Refresh result",
  "Повторить отправку": "Retry submission",
  "Отменить решение": "Cancel decision",
  "Решение не отправлено. Замечание осталось в черновике.": "Decision not submitted. The comment remains in the draft.",
  "Ожидает решения": "Awaiting decision",
  "Результат принят": "Result accepted",
  "Доработка подтверждена. Ожидает передачи исполнителю; работа ещё не началась.": "Rework confirmed. Awaiting dispatch to the executor; work has not started.",
  "В работе · подтверждено исполнителем": "In progress · confirmed by the executor",
  "Решение сохранено в локальной очереди. Подтверждения сервиса и запуска нет.": "Decision saved in the local queue. No service acknowledgement or start confirmation.",
  "Исход отправки неизвестен. Повтор использует то же решение.": "Submission outcome unknown. Retrying uses the same decision.",
  "Результат обновлён. Проверь ревизию перед решением.": "Result refreshed. Check the revision before deciding.",
  "Результат недоступен. Решение не отправлено.": "Result unavailable. Decision not submitted.",
  "Добавь замечание для доработки (до 8000 символов).": "Add a rework comment (up to 8000 characters).",
  "Решение подтверждено сервисом.": "Decision acknowledged by the service.",
  "Результат изменился (409). Обнови результат и проверь новую ревизию. Замечание сохранено.": "Result changed (409). Refresh it and check the new revision. Your comment is preserved.",
  "Исход отправки неизвестен. Замечание сохранено; повтор отправит исходное решение.": "Submission outcome unknown. Your comment is preserved; retrying submits the original decision.",
  "Дождись завершения отправки решения.": "Wait for the decision submission to finish.",
  "Не удалось проверить импорт сна. Повтори попытку.": "Could not check sleep import. Try again.",
  "Сон импортируется из Health Connect на телефоне Android и приходит сюда через синхронизацию.": "Sleep is imported from Health Connect on an Android phone and arrives here through sync.",
  "Health Connect недоступен. Установи или обнови его на телефоне.": "Health Connect unavailable. Install or update it on your phone.",
  "Разреши Cicada читать сон в Health Connect. Импортированные ранее записи сохранены.": "Allow Cicada to read sleep in Health Connect. Previously imported records are preserved.",
  "Заверши системный запрос Health Connect, затем проверь сон. Разрешение ещё не подтверждено.": "Complete the Health Connect system prompt, then check sleep. Permission is not confirmed yet.",
  "Для чтения сна открой Cicada на телефоне.": "Open Cicada on your phone to read sleep.",
  "Последний импорт сна не завершён. Сохранённые записи не потеряны; повтори попытку.": "The last sleep import did not finish. Stored records are preserved; try again.",
  "Доступ разрешён. Первый импорт сна ещё не подтверждён.": "Access allowed. The first sleep import is not confirmed yet.",
  "В Health Connect не найдено записей сна. Проверь, что Samsung Health или другое приложение передаёт туда сон.": "No sleep records found in Health Connect. Check that Samsung Health or another app sends sleep there.",
  "Сон": "Sleep",
  "Проверяем Health Connect…": "Checking Health Connect…",
  "Разрешить чтение сна": "Allow sleep access",
  "Проверить сон сейчас": "Check sleep now",
  "Повторить проверку": "Retry check",
  "Проверяем записи сна…": "Checking sleep records…",
  "Разрешить чтение в фоне": "Allow background access",
  "Фоновое чтение разрешено. Android определяет время запуска; обновление может задерживаться.": "Background access allowed. Android controls the schedule; updates may be delayed.",
  "Фоновое чтение не разрешено. Пока сон проверяется при открытом приложении.": "Background access not allowed. Sleep is checked while the app is open.",
  "На этом телефоне Health Connect не поддерживает чтение в фоне. Сон проверяется при открытом Cicada.": "Health Connect does not support background access on this phone. Sleep is checked while Cicada is open.",
  "После перерыва повторно проверены последние 30 дней. Более ранние записи сохранены, но изменения в них пока не подтверждены источником.": "The last 30 days were checked again after a break. Earlier records are preserved, but changes to them have not been confirmed by the source yet.",
  "Не удалось проверить импорт. Повтори попытку.": "Could not check import. Try again.",
  "Прогулки и шаги импортируются из Health Connect на телефоне Android и приходят сюда через синхронизацию.": "Walks and steps are imported from Health Connect on an Android phone and arrive here through sync.",
  "Заверши системный запрос Health Connect, затем проверь импорт. Разрешение ещё не подтверждено.": "Complete the Health Connect system prompt, then check import. Permission is not confirmed yet.",
  "прогулок": "walks",
  "шагов": "steps",
  "прогулки": "walks",
  "шаги": "steps",
  "В Health Connect не найдено прогулок с типом walking. Cicada не выводит прогулки из одних шагов.": "No walking sessions found in Health Connect. Cicada does not infer walks from steps alone.",
  "В Health Connect не найдено дневных итогов шагов. Пустой день не считается нулевым итогом.": "No daily step totals found in Health Connect. An empty day is not treated as a zero total.",
  "Прогулки и шаги": "Walks and steps",
  "Прогулки": "Walks",
  "Шаги": "Steps",
  "Разрешить чтение прогулок и шагов": "Allow walks and steps access",
  "Проверить прогулки и шаги сейчас": "Check walks and steps now",
  "Проверяем прогулки…": "Checking walks…",
  "Проверяем шаги…": "Checking steps…",
  "Разрешить недостающий доступ": "Allow missing access",
  "Фоновое чтение не разрешено. Пока данные проверяются при открытом приложении.": "Background access not allowed. Data is checked while the app is open.",
  "На этом телефоне Health Connect не поддерживает чтение в фоне. Данные проверяются при открытом Cicada.": "Health Connect does not support background access on this phone. Data is checked while Cicada is open.",
  "Результат · ревизия ": "Result · revision ",
  " · версия задачи ": " · task version ",
  " · результат ": " · result ",
  "Импортировано записей сна: ": "Sleep records imported: ",
  "Последняя проверка сна: ": "Last sleep check: ",
  "Для чтения ": "To read ",
  " открой Cicada на телефоне.": " open Cicada on your phone.",
  "Последний импорт ": "Last import of ",
  " не завершён. Сохранённые записи не потеряны; повтори попытку.": " did not finish. Stored records are preserved; try again.",
  "Разреши Cicada читать ": "Allow Cicada to read ",
  " в Health Connect. Ранее импортированные записи сохранены.": " in Health Connect. Previously imported records are preserved.",
  "Доступ к ": "Access to ",
  " разрешён. Первый импорт ещё не подтверждён.": " allowed. The first import is not confirmed yet.",
  "Импортировано прогулок: ": "Walks imported: ",
  "Импортировано дневных итогов шагов: ": "Daily step totals imported: ",
  "Последняя проверка прогулок и шагов: ": "Last walks and steps check: ",
  "Запланировано": "Planned",
  "Проверка": "Checking",
  "Нужно решение": "Decision needed",
  "Готово": "Done",
  "Отменено": "Cancelled",
  "Неизвестно": "Unknown",
  "Свежее наблюдение": "Fresh observation",
  "Устаревшее наблюдение": "Stale observation",
  "Свежесть неизвестна": "Observation freshness unknown",
  " Сохранение ": " Saving ",
  " не подтверждено; черновик остался в форме.": " is unconfirmed; the draft remains in the form.",
  "Нужен хотя бы один процесс.": "At least one process is required.",
  "У процесса неверный идентификатор. Отмени изменения и повтори.": "The process identifier is invalid. Discard changes and retry.",
  "Укажи название процесса.": "Enter a process name.",
  "Добавь хотя бы одну стадию.": "Add at least one stage.",
  "У стадии неверный идентификатор. Удали её и добавь снова.": "The stage identifier is invalid. Remove it and add it again.",
  "Укажи название стадии.": "Enter a stage name.",
  "Неподдерживаемый формат процессов. Сохранение остановлено, чтобы не потерять данные.": "Unsupported process format. Saving stopped to preserve data.",
  "Процессы изменены на другом устройстве. Нажми «Отменить изменения», чтобы загрузить новую версию, и повтори.": "Processes changed on another device. Use Discard changes to load the new version, then retry.",
  "Можно сохранить до 20 процессов.": "You can save up to 20 processes.",
  "Сократи название процесса до 80 символов.": "Shorten the process name to 80 characters.",
  "Сократи название стадии до 80 символов.": "Shorten the stage name to 80 characters.",
  "Назови процесс.": "Name the process.",
  "У стадии неверный идентификатор. Отмени изменения и повтори.": "The stage identifier is invalid. Discard changes and retry.",
  "Назови стадию или удали её.": "Name the stage or remove it.",
  "В процессе можно держать до 30 стадий.": "A process can have up to 30 stages.",
  "Настройки": "Settings",
  "Изменить цель": "Edit goal",
  "Новая подцель": "New subgoal",
  "Новая цель": "New goal",
  "Сохрани то, к чему хочешь прийти. Срок можно добавить позже.": "Save what you want to achieve. You can add a deadline later.",
  "Сохранить цель": "Save goal",
  "Например, подготовить учебный проект": "For example, prepare a learning project",
  "Например: самостоятельно описываю API-контракт": "For example: describe an API contract independently",
  "Например, л": "For example, L",
  "Напиши, к чему хочешь прийти.": "Describe what you want to achieve.",
  "Сократи название цели до 500 символов.": "Shorten the goal title to 500 characters.",
  "Введи срок полностью или очисти поле даты.": "Enter a complete deadline or clear the date.",
  "Выбери долгосрочную цель или ежедневную норму.": "Choose a long-term goal or a daily target.",
  "Укажи положительное целевое значение.": "Enter a positive target value.",
  "Укажи неотрицательный прогресс или очисти поле.": "Enter non-negative progress or clear the field.",
  "Не удалось сохранить цель. Текст остался в форме — попробуй ещё раз.": "Could not save the goal. Your text remains in the form; try again.",
  "Удалить цель": "Delete goal",
  "Связанные задачи и события сохранятся без этой цели.": "Linked tasks and events will remain without this goal.",
  "Не удалось удалить цель. Попробуй ещё раз.": "Could not delete the goal. Try again.",
  "Покупки, поездки и впечатления без плана. Если нужно накопить — преврати желание в цель.": "Purchases, trips and experiences without a plan. Turn a wish into a goal if you need to save for it.",
  "Сохрани то, к чему хочешь прийти. Задачи можно добавить позже.": "Save what you want to achieve. You can add tasks later.",
  "Каждый день: {0} {1}": "Every day: {0} {1}",
  "Тип не выбран": "Type not selected",
  "Этап не выбран": "Stage not selected",
  "{0} из {1}{2}": "{0} of {1}{2}",
  "до {0}": "by {0}",
  "Подцели: {0}": "Subgoals: {0}",
  "Главная подцель: {0}": "Primary subgoal: {0}",
  "Долгосрочные цели": "Long-term goals",
  "Достигнутые цели": "Achieved goals",
  "Ежедневные нормы": "Daily targets",
  "Без типа — выбери, как учитывать": "No type selected — choose how to track",
  "Состояние целей и этапы не удалось прочитать. Сами цели доступны.": "Could not read goal state and stages. The goals themselves are available.",
  "Задача сейчас выполняется. Главную цель можно сменить.": "A task is running. You can change the primary goal.",
  "Главная цель выбрана. Задача начнётся только после нажатия «Начать».": "Primary goal selected. The task starts only when you press Start.",
  "Не удалось сменить главную цель. Повтори выбор; текущая задача сохранена.": "Could not change the primary goal. Try selecting again; the current task is preserved.",
  "Цель создана из желания.": "Goal created from a wish.",
  "Цель сохранена. Можно выбрать её главной, когда будешь готов.": "Goal saved. You can choose it as primary when ready.",
  "Цель удалена. Задачи сохранены.": "Goal deleted. Tasks preserved.",
  "Файл слишком большой для импорта навыков.": "The file is too large to import skills.",
  "Не удалось прочитать JSON.": "Could not read JSON.",
  "В JSON нет корректных навыков.": "The JSON contains no valid skills.",
  "Не хватает связи задачи и навыка.": "The task-to-skill link is missing.",
  "Навык уже изменён. Обнови цель и повтори привязку задачи.": "The skill has changed. Refresh the goal and link the task again.",
  "Эта запись изменена на другом устройстве. Черновик остаётся в открытой форме. Открой запись заново перед повторным сохранением.": "This record changed on another device. The draft remains in the open form. Reopen the record before saving again.",
  "SQL, API или название": "SQL, API or a name",
  "Уровень {0}": "Level {0}",
  "Выбрано: {0}": "Selected: {0}",
  "Не хватает цели или native API.": "The goal or native API is missing.",
  "Цель изменена на другом устройстве. Черновик сохранён в открытом редакторе. Закрой его и открой цель заново перед повтором.": "The goal changed on another device. The draft remains in the open editor. Close it and reopen the goal before retrying.",
  "Не удалось сохранить изменения. Ничего не применено — повтори действие.": "Could not save changes. Nothing was applied; try again.",
  "Не удалось сохранить.": "Could not save.",
  "Изменить навык": "Edit skill",
  "Тема нужна, чтобы группировать развитие. Подтверждение добавляется после практики.": "A topic groups development. Add evidence after practice.",
  "SQL, API, требования…": "SQL, API, requirements…",
  "Заполни название и тему.": "Enter a title and topic.",
  "Опиши проверяемый результат: работа, ссылка или краткая проверка.": "Describe a verifiable result: work, a link or a brief check.",
  "Сохранить подтверждение": "Save evidence",
  "Изменить этап": "Edit stage",
  "Новый этап": "New stage",
  "Этап — промежуточный результат. Навыки и срок можно добавить по желанию.": "A stage is an intermediate result. Skills and a deadline are optional.",
  "Сохранить этап": "Save stage",
  "Дай этапу название.": "Name the stage.",
  "Проверь срок этапа.": "Check the stage deadline.",
  "Выбор не меняет текущую задачу. Сначала выбери тему, затем навык.": "This selection leaves the current task unchanged. Choose a topic, then a skill.",
  "Применить": "Apply",
  "Импорт навыков JSON": "Import skills from JSON",
  "Ожидается JSON с skills или development export. Импорт добавляет уникальные навыки к этой цели.": "Provide JSON with skills or a development export. Import adds unique skills to this goal.",
  "Импортировать": "Import",
  "Текущий · ": "Current · ",
  " · Навыки: {0} из {1} подтверждено": " · Skills: {0} of {1} confirmed",
  " · До {0}": " · By {0}",
  "Показан": "Shown",
  "Действия с этапом: {0}": "Stage actions: {0}",
  "Задачи навыка": "Skill tasks",
  "Задача {0}": "Task {0}",
  " · Выполнено": " · Completed",
  "Подтверждено": "Confirmed",
  "Без подтверждения": "No evidence",
  "Практика: {0}": "Practice: {0}",
  "Изменить результат": "Edit result",
  "Подтвердить": "Confirm",
  "Срок цели: {0}": "Goal deadline: {0}",
  "Навык в этапе «{0}»": "Skill in stage “{0}”",
  "Сейчас развиваю": "Developing now",
  "В этапе пока нет навыков": "No skills in this stage yet",
  "Не выбрано": "Not selected",
  "Сменить или очистить": "Change or clear",
  "Выбрать навык": "Choose skill",
  "Текущий этап «{0}» завершён. Покажи следующий этап и нажми «Сделать текущим».": "Current stage “{0}” is completed. Show the next stage and press Make current.",
  "{0} из {1}": "{0} of {1}",
  "{0}% · {1} из {2} подтверждено": "{0}% · {1} of {2} confirmed",
  "Импорт JSON": "Import JSON",
  "Завершить этап?": "Complete stage?",
  "Этап останется текущим, пока ты явно не выберешь следующий.": "The stage remains current until you explicitly choose the next one.",
  "Удалить этап?": "Delete stage?",
  "Навыки и их подтверждения останутся в цели.": "Skills and their evidence will remain in the goal.",
  "Исключить навык из цели?": "Remove skill from goal?",
  "Навык выйдет из этапов и фокуса, но связанные задачи не будут удалены.": "The skill will leave stages and focus. Linked tasks will remain.",
  "Выбери ближайший этап или развитие всей цели. Текущая задача не изменится.": "Choose the next stage or develop the whole goal. The current task stays unchanged.",
  "Выбрать этап": "Choose stage",
  "Навыков: {0}": "Skills: {0}",
  " · до ": " · by ",
  "Этот этап уже недоступен.": "This stage is no longer available.",
  "Остановить выполнение и выбрать другую задачу. Учтённое время сохранится.": "Stop work and choose another task. Tracked time will be preserved.",
  "Сменить задачу": "Change task",
  "Следующая задача": "Next task",
  "Открыть календарь": "Open calendar",
  "Открыть цель": "Open goal",
  "Цель достигнута · показана на дашборде": "Goal achieved · shown on dashboard",
  "Показана на дашборде": "Shown on dashboard",
  "Срок: {0}": "Deadline: {0}",
  "Срок не задан": "No deadline",
  "Закрыть цель": "Close goal",
  "Готово, когда": "Done when",
  "Подцели": "Subgoals",
  "Учтено: {0} из {1} {2}": "Tracked: {0} of {1} {2}",
  "События": "Events",
  "Повторения": "Occurrences",
  "Учтено {0}": "Tracked {0}",
  "{0} из {1} мин": "{0} of {1} min",
  "{0} · запущено: {1}": "{0} · running: {1}",
  "Выбери то, на чём хочешь сосредоточиться.": "Choose what you want to focus on.",
  "Пока без цели": "No goal for now",
  "Цель достигнута": "Goal achieved",
  "Выбрано": "Selected",
  "По этому названию целей не найдено.": "No goals found with this title.",
  "Сохранённых целей пока нет. Добавь цель в разделе «Цели».": "No saved goals yet. Add one in Goals.",
  "Не удалось выбрать цель. Повтори выбор.": "Could not select the goal. Try again.",
  "Выбранная цель недоступна": "Selected goal unavailable",
  "Выбери, к чему хочешь прийти": "Choose what you want to achieve",
  "Цель недоступна": "Goal unavailable",
  "Главная цель не выбрана": "Primary goal not selected",
  "Текущий этап: {0}": "Current stage: {0}",
  "Выбери другую цель, чтобы продолжить.": "Choose another goal to continue.",
  "Выбери другую цель или сохрани новую.": "Choose another goal or save a new one.",
  "Следующая задача по цели: {0}": "Next task for goal: {0}",
  "Задач по цели пока нет": "No tasks for this goal yet",
  "Сменить": "Change",
  "Выбрать главную цель": "Choose primary goal",
  "Загружаем текущую задачу…": "Loading current task…",
  "Начни задачу из списка или выбери цель.": "Start a task from the list or choose a goal.",
  "Для этой цели пока нет подходящей задачи.": "No suitable task for this goal yet.",
  "Открыть задачу": "Open task",
  "Свяжи задачу с целью в календаре. Запуск остаётся твоим решением.": "Link a task to the goal in Calendar. You decide when to start.",
  "Выбор изменён на другом устройстве. Повтори загрузку актуального состояния.": "The selection changed on another device. Reload the current state.",
  "Не удалось обновить текущую задачу. Последний выбор сохранён.": "Could not refresh the current task. The last selection is preserved.",
  "Выбор изменён на другом устройстве. Нажми «Повторить», чтобы загрузить актуальное состояние.": "The selection changed on another device. Press Retry to load the current state.",
  "Для смены цели поставь текущую задачу на паузу.": "Pause the current task before changing the goal.",
  "Сейчас запущена другая задача. Обнови экран перед продолжением.": "Another task is running. Refresh the screen before continuing.",
  "Задача уже завершена или недоступна. Обнови экран.": "The task is completed or unavailable. Refresh the screen.",
  "Действие применено, но не удалось сохранить выбор. Повтор сохранит его без повторного запуска задачи.": "The action was applied, but the selection could not be saved. Retrying will save it without starting the task again.",
  "Не удалось запустить задачу.": "Could not start the task.",
  "Не удалось поставить задачу на паузу.": "Could not pause the task.",
  "Не удалось завершить задачу.": "Could not complete the task.",
  "Не удалось сменить задачу. Текущая задача сохранена.": "Could not change the task. The current task is preserved.",
  "Не удалось сохранить выбор.": "Could not save the selection.",
  "Задача приостановлена.": "Task paused.",
  "Выполнение остановлено. Учтённое время сохранено. Выбери другую задачу.": "Work stopped. Tracked time preserved. Choose another task.",
  "Цель выбрана.": "Goal selected.",
  "Задача выбрана. Нажми «Начать», когда будешь готов.": "Task selected. Press Start when ready.",
  "Выбор обновлён.": "Selection updated.",
  "Состояние обновилось. Проверь задачу перед действием.": "The state changed. Check the task before acting.",
  "Дождись завершения текущего действия.": "Wait for the current action to finish.",
  "Не удалось обновить текущую задачу. Повтори выбор.": "Could not refresh the current task. Select again.",
  "Эта цель больше недоступна.": "This goal is no longer available.",
  "Достигнутую цель нельзя выбрать главной.": "An achieved goal cannot be selected as primary.",
  "Предыдущая задача сейчас недоступна. Повтори загрузку.": "The previous task is unavailable. Reload.",
  "{0} задача": "{0} task",
  "{0} задач": "{0} tasks",
  "{0} событие": "{0} event",
  "{0} событий": "{0} events",
  "{0} повторение": "{0} occurrence",
  "{0} повторений": "{0} occurrences",
  "{0} из {1} навыков этапа подтверждено": "{0} of {1} stage skills confirmed",
  "{0} из {1} навыков цели подтверждено": "{0} of {1} goal skills confirmed",
  "Неподдерживаемый формат развития. Сохранение остановлено, чтобы не потерять данные.": "Unsupported development format. Saving stopped to preserve data.",
  "Не удалось прочитать дела и правила. Сохранённые данные не изменены.": "Could not read activities and rules. Saved data is unchanged.",
  "Расписание изменено на другом устройстве. Обнови вид и повтори действие.": "The schedule changed on another device. Refresh the view and retry.",
  "{0} и ": "{0} on ",
  "Настройка «{0}» изменилась на другом устройстве. Закрой и открой настройки, чтобы загрузить актуальные значения.": "The {0} setting changed on another device. Close and reopen Settings to load the current values.",
  "Предыдущий период": "Previous period",
  "Следующий период": "Next period",
  "Изменения и удаление — в приложении-источнике. Начало дня отмечается отдельно.": "Edit or delete in the source application. Day start is recorded separately."
};
export function copyForLanguage(language = 'ru') {
  const en = typeof language === 'string' && language.toLowerCase().startsWith('en');
  const copy = value => en && Object.hasOwn(english, value) ? english[value] : value;
  copy.format = (value, ...parameters) => copy(value).replace(/\{(\d+)\}/g, (_, index) => String(parameters[Number(index)] ?? ''));
  copy.locale = en ? 'en' : 'ru-RU';
  return copy;
}
export function createUiCopy(document) {
  const copy = value => copyForLanguage(document?.documentElement?.lang || 'ru')(value);
  copy.format = (value, ...parameters) => copy(value).replace(/\{(\d+)\}/g, (_, index) => String(parameters[Number(index)] ?? ''));
  Object.defineProperty(copy, 'locale', { get: () => copyForLanguage(document?.documentElement?.lang || 'ru').locale });
  return copy;
}
