const english = {
  "Запланирован": "Planned",
  "В работе": "In progress",
  "Жду ответа": "Waiting for a response",
  "Готов": "Done",
  "Ближайший шаг задачи": "Next task step",
  "Указать ближайший шаг": "Set next step",
  "Шаги и результат": "Steps and result",
  "Отмечай ход работы вручную. Шаги не меняют этап или таймер задачи.": "Track progress manually. Steps do not change the task stage or timer.",
  "Шаги задачи": "Task steps",
  "Следующий шаг": "Next step",
  "Добавить шаг": "Add step",
  "Результат задачи": "Task result",
  "Сохранить результат": "Save result",
  "Отменить ввод": "Discard input",
  "Повторить чтение": "Read again",
  "Обновить состояние": "Refresh status",
  "Ближайший шаг ещё не указан.": "No next step has been set.",
  "Незавершённые шаги ждут ответа.": "Unfinished steps are waiting for a response.",
  "Выбрать другой шаг": "Choose another step",
  "Шаги и результат · шаги не указаны": "Steps and result · no steps set",
  "Статус шага сохранён.": "Step status saved.",
  "Ожидание": "Waiting",
  "Завершён": "Completed",
  "Ошибка": "Error",
  "Отменён": "Cancelled",
  "неизвестно": "unknown",
  "Статус внешнего исполнителя недоступен. Расходы неизвестны.": "External executor status unavailable. Usage is unknown.",
  "Внешний исполнитель не связан. Автоматическое выполнение не запускалось.": "No external executor is linked. Automatic execution has not started.",
  "Читаем ближайший шаг…": "Reading the next step…",
  "Загрузка шагов…": "Loading steps…",
  "Импортированный реестр недоступен. Статус исполнения неизвестен.": "Imported registry unavailable. Execution status unknown.",
  "Шаги и результат · данные недоступны": "Steps and result · data unavailable",
  "Ближайший шаг не обновлён. Ниже — последнее подтверждённое состояние.": "The next step was not refreshed. The last confirmed state is shown below.",
  "Ближайший шаг неизвестен: не удалось прочитать данные.": "Next step unknown: could not read the data.",
  "Не удалось прочитать шаги. Формат может быть новее этой версии; данные сохранены без изменений. Сохранение недоступно.": "Could not read steps. The format may be newer than this version; stored data is unchanged. Saving is unavailable.",
  "Сохранение…": "Saving…",
  "Не удалось сохранить. Данные не подтверждены; перечитай состояние и повтори.": "Could not save. Data is unconfirmed; read the status again and retry.",
  "Шаг сохранён.": "Step saved.",
  "Результат сохранён.": "Result saved.",
  "Несохранённый ввод отменён.": "Unsaved input discarded.",
  "Дождись сохранения шагов.": "Wait for the steps to finish saving.",
  "Сохрани шаг или результат перед закрытием.": "Save the step or result before closing.",
  "Выбор следующего действия": "Next action selection",
  "Настройки Cicada": "Cicada settings",
  "Сохранить": "Save",
  "Сохранить календарь": "Save calendar",
  "Разделы настроек": "Settings sections",
  "Отмена": "Cancel",
  "Отмена и закрыть настройки": "Cancel and close settings",
  "Повторить загрузку": "Retry loading",
  "Загружаем настройки выбора…": "Loading selection settings…",
  "Загружаем настройки календаря…": "Loading calendar settings…",
  "Подтверждение закрытия с несохранёнными изменениями": "Confirm closing with unsaved changes",
  "Есть несохранённые изменения.": "There are unsaved changes.",
  "Продолжить редактирование": "Continue editing",
  "Закрыть без сохранения": "Close without saving",
  "Закрыть": "Close",
  "Первый день недели": "First day of the week",
  "Вид при запуске": "Startup view",
  "Плотность интерфейса": "Interface density",
  "Здоровье: сон, прогулки и шаги": "Health: sleep, walks and steps",
  "В этой сборке интеграция Jira недоступна. Здесь нет данных о подключении или импорте. Подключение на другом устройстве нужно проверить на том устройстве.": "Jira integration is unavailable in this build. There is no connection or import data here. A connection on another device must be checked on that device.",
  "Настройки календаря сохранены. Черновик этапов ещё не сохранён — сохрани его во вкладке «Этапы задач» или закрой настройки с отменой.": "Calendar settings saved. The stage draft is not saved yet: save it in Task stages or close settings and discard it.",
  "Настройки календаря сохранены. Изменения подключения ещё не сохранены.": "Calendar settings saved. Connection changes are not saved yet.",
  "Ошибка сохранения.": "Save error.",
  "настроек выбора": "selection settings",
  "календаря": "calendar",
  "Процессы задач": "Task processes",
  "Стадии для задач с процессом. Переименование не меняет задачи. Если удалить стадию, её задачи покажут «Стадия удалена», пока ты не выберешь другую.": "Stages for tasks with a process. Renaming does not change tasks. Deleting a stage makes its tasks show Deleted stage until you select another one.",
  "Загружаем процессы…": "Loading processes…",
  "＋ Новый процесс": "＋ New process",
  "Сохранить процессы": "Save processes",
  "Отменить изменения": "Discard changes",
  "Встроенный процесс": "Built-in process",
  "Процесс": "Process",
  "Новый процесс": "New process",
  "Например, Ремонт": "For example, Renovation",
  "Название процесса": "Process name",
  "процесс без названия": "untitled process",
  "Название стадии": "Stage name",
  "процесс": "process",
  "＋ Стадия": "＋ Stage",
  "без названия": "untitled",
  "Убрать": "Remove",
  "Один процесс": "One process",
  "Не удалось загрузить процессы.": "Could not load processes.",
  "Сохраняем процессы…": "Saving processes…",
  "Процессы сохранены.": "Processes saved.",
  "Не удалось сохранить процессы. Изменения остались в форме.": "Could not save processes. Changes remain in the form.",
  "Изменения отменены.": "Changes discarded.",
  "Синхронизация": "Synchronization",
  "Загружаем состояние…": "Loading status…",
  "Состояние этого устройства. Другое устройство получит изменения после своего подключения.": "Status of this device. Other devices receive changes after connecting.",
  "Код подключения": "Connection code",
  "Вставь код подключения устройства": "Paste the device connection code",
  "Код подключения устройства": "Device connection code",
  "Показать код": "Show code",
  "Скрыть код": "Hide code",
  "Синхронизация включена": "Synchronization enabled",
  "Сохранить подключение": "Save connection",
  "Синхронизировать сейчас": "Sync now",
  "Разобрать сохранённые версии": "Review saved versions",
  "Нет доступа к сохранённому ключу синхронизации. Локальные данные сохранены. После восстановления доступа к хранилищу ключей перезапусти Cicada.": "The stored sync key is inaccessible. Local data is preserved. Restart Cicada after restoring access to the key store.",
  "Подключить устройство": "Connect device",
  "Состояние синхронизации недоступно.": "Sync status unavailable.",
  "Синхронизация приостановлена: ключ подключения недоступен.": "Sync paused: connection key unavailable.",
  "Устройство ещё не подключено.": "This device is not connected yet.",
  "Синхронизация выключена.": "Synchronization disabled.",
  "Идёт обмен изменениями…": "Exchanging changes…",
  "Нет сети. Изменения остаются на этом устройстве.": "Offline. Changes remain on this device.",
  "Последний обмен не завершён. Изменения ожидают повторной попытки.": "The last exchange did not finish. Changes are awaiting a retry.",
  "Подключение включено.": "Connection enabled.",
  "Сеть недоступна. Повторим обмен после подключения.": "Network unavailable. The exchange will retry after connecting.",
  "Код подключения больше не принят сервером.": "The server no longer accepts the connection code.",
  "Устройство не имеет доступа к обмену.": "This device has no access to the exchange.",
  "Для продолжения синхронизации обнови Cicada на этом устройстве.": "Update Cicada on this device to continue syncing.",
  "Сервер просит повторить попытку позже.": "The server asks to retry later.",
  "На сервере не хватает места для изменений.": "The server has insufficient space for changes.",
  "Подключение изменилось. Повтори обмен с текущим подключением.": "The connection changed. Retry the exchange using the current connection.",
  "Проверь код подключения.": "Check the connection code.",
  "Не удалось создать резервную копию перед включением синхронизации.": "Could not create a backup before enabling sync.",
  "Не удалось включить фоновую синхронизацию. Повтори включение синхронизации.": "Could not enable background sync. Try enabling sync again.",
  "Последний обмен завершился ошибкой. Локальные изменения сохранены.": "The last exchange failed. Local changes are preserved.",
  "Успешный обмен ещё не подтверждён.": "A successful exchange has not been confirmed yet.",
  "Не удалось прочитать состояние синхронизации.": "Could not read sync status.",
  "Код подключения должен содержать JSON. Проверь, что он скопирован целиком.": "The connection code must contain JSON. Check that you copied it in full.",
  "Вставь код подключения этого устройства.": "Paste the connection code for this device.",
  "Не удалось сохранить подключение. Проверь код и повтори попытку.": "Could not save the connection. Check the code and try again.",
  "Не удалось завершить обмен. Локальные изменения сохранены; повтори попытку при доступной сети.": "Could not finish the exchange. Local changes are preserved; retry when online.",
  "Сравни названия и фрагменты полей перед выбором. Выбор текущей версии закрывает только эту запись на этом устройстве.": "Compare titles and field excerpts before choosing. Keeping the current version closes only this entry on this device.",
  "Обновить список": "Refresh list",
  "К списку": "Back to list",
  "Назад": "Previous",
  "Далее": "Next",
  "Запись уже удалена. Сохранённая версия не может отменить удаление.": "The record is already deleted. A saved version cannot undo deletion.",
  "Версии относятся к разным записям. Замена недоступна.": "The versions belong to different records. Replacement is unavailable.",
  "Связанная задача или цель ещё не получена. Обнови список после синхронизации.": "The linked task or goal has not arrived yet. Refresh the list after syncing.",
  "У записи есть связанные задачи или цели. Сначала обнови их связи.": "The record has linked tasks or goals. Update those links first.",
  "Такая связь создаст замкнутую цепочку целей. Выбери другую родительскую цель.": "This link would create a goal cycle. Choose another parent goal.",
  "Выбранная родительская цель не поддерживает эту связь.": "The selected parent goal does not support this link.",
  "Сначала приостанови текущую задачу, затем обнови список.": "Pause the current task first, then refresh the list.",
  "Сохранённая версия содержит старый запуск задачи. Автоматическая замена недоступна.": "The saved version contains an old task run. Automatic replacement is unavailable.",
  "Формат записи пока не поддерживается. Доступен только просмотр.": "The record format is not supported yet. Only viewing is available.",
  "Записи нет на этом устройстве.": "The record is absent on this device.",
  "Запись удалена.": "The record is deleted.",
  "Эту версию нельзя безопасно отобразить.": "This version cannot be displayed safely.",
  "Настройки или связи записи.": "Record settings or links.",
  "На этом устройстве": "On this device",
  "Входящая версия": "Incoming version",
  "Сохранённая версия": "Saved version",
  "Эту версию пока нельзя безопасно применить. Обнови список после синхронизации.": "This version cannot be applied safely yet. Refresh the list after syncing.",
  "Оставить текущее": "Keep current",
  "Использовать эту версию": "Use this version",
  "Загружаем версии…": "Loading versions…",
  "Неразобранных версий нет.": "No versions remain to review.",
  "Не удалось загрузить версии. Попробуй ещё раз.": "Could not load versions. Try again.",
  "Сохраняем выбор…": "Saving your choice…",
  "Выбранная версия сохранена. Изменение ожидает синхронизации.": "Selected version saved. The change is awaiting sync.",
  "Текущая версия сохранена.": "Current version saved.",
  "Запись изменилась, пока ты сравнивал версии. Обнови список и выбери заново.": "The record changed while you compared versions. Refresh the list and choose again.",
  "Не удалось применить выбор. Записи сохранены; обнови список.": "Could not apply the choice. Records are preserved; refresh the list.",
  "Файлы и источники": "Files and sources",
  "Выбери папку и проверь структуру перед сохранением. Данные не читаются, задачи не перезаписываются. Видимость и размещение применяются к разделам источников в личном Cicada. Автоматического обновления нет.": "Choose a folder and check its structure before saving. Data is not read and tasks are not overwritten. Visibility and placement apply to source sections in personal Cicada. There is no automatic refresh.",
  "Сохранить источники": "Save sources",
  "Абсолютный путь к папке": "Absolute folder path",
  "Папка не проверена.": "Folder not checked.",
  "Путь изменён. Проверь папку перед сохранением.": "Path changed. Check the folder before saving.",
  "Выбор папки недоступен. Вставь абсолютный путь и проверь его.": "Folder picker unavailable. Paste an absolute path and check it.",
  "Показывать раздел": "Show section",
  "Предпочитать локальный private Git": "Prefer local private Git",
  "Размещение": "Placement",
  "Tasks • перед обычными задачами": "Tasks • before regular tasks",
  "Projects • после источников задач": "Projects • after task sources",
  "Проверка не удалась: требуется существующая локальная папка без ссылок и ожидаемые типы. Содержимое не читалось.": "Check failed: an existing local folder without links and with expected types is required. Contents were not read.",
  "Настройки сохранены. Разделы источников обновлены. Файлы не импортированы; режим ручной.": "Settings saved. Source sections updated. Files were not imported; mode is manual.",
  "Сохранение не подтверждено. Проверь абсолютные пути или открой настройки заново.": "Saving is unconfirmed. Check absolute paths or reopen settings.",
  "Настройки загружены. Источники не проверены; автоматического обновления нет.": "Settings loaded. Sources have not been checked; there is no automatic refresh.",
  "Источники не настроены. Можно пропустить и вернуться позже.": "Sources are not configured. You can skip and return later.",
  "Настройки недоступны; сохранение заблокировано.": "Settings unavailable; saving is blocked.",
  "Подключить папки данных?": "Connect data folders?",
  "Можно настроить локальные источники сейчас или пропустить. Задачи доступны без подключения.": "You can configure local sources now or skip. Tasks are available without a connection.",
  "Настроить источники": "Configure sources",
  "Пропустить": "Skip",
  "Не удалось сохранить выбор. Попробуй снова.": "Could not save your choice. Try again.",
  "есть": "present",
  "нет": "absent",
  "Импортированный рабочий реестр": "Imported work registry",
  "Снимки engineering-задач, опубликованные родителем. Это не live-поток и не запуск исполнителя.": "Engineering task snapshots published by the parent. This is not a live stream or executor launch.",
  "JSON снимка": "Snapshot JSON",
  "Предварительный просмотр": "Preview",
  "Импортировать просмотренный снимок": "Import previewed snapshot",
  "Импортированные работы": "Imported work",
  "Операция": "Operation",
  "Ожидает": "Waiting for",
  "Результат": "Result",
  "Предпросмотр. Данные ещё не сохранены.": "Preview. Data has not been saved yet.",
  "Снимок некорректен или содержит неподдерживаемые поля. Ничего не сохранено.": "The snapshot is invalid or contains unsupported fields. Nothing was saved.",
  "Снимок сохранён. Задачи и ручные шаги не изменены.": "Snapshot saved. Tasks and manual steps are unchanged.",
  "Этот снимок уже сохранён.": "This snapshot is already saved.",
  "Импорт не подтверждён. Проверь sequence или перечитай состояние.": "Import unconfirmed. Check sequence or read the status again.",
  "Сохранённый реестр недоступен. Импорт не выполнялся.": "Stored registry unavailable. No import was performed.",
  "Импорт личных задач из файла": "Import personal tasks from a file",
  "Предпросмотр ничего не записывает. Импорт создаёт резервную копию. Архив — только по явно указанным ID личных шаблонов.": "Preview writes nothing. Import creates a backup. Archiving applies only to explicitly listed personal template IDs.",
  "Файл личных задач": "Personal tasks file",
  "Создать backup и импортировать": "Create backup and import",
  "Я сохранил экспорт и план восстановления": "I saved the export and recovery plan",
  "Сохранить экспорт и план восстановления": "Save export and recovery plan",
  "Сохранение и проверка экспорта не подтверждены.": "Export saving and verification are unconfirmed.",
  "Выбери JSON до 64 КБ.": "Choose a JSON file up to 64 KB.",
  "Создать": "Create",
  "Обновить": "Update",
  "Уже записано": "Already stored",
  "Описание и метки": "Description and tags",
  "без проектов": "no projects",
  "Проверь список, сохрани экспорт и подтверди его сохранение.": "Check the list, save the export and confirm that you saved it.",
  "Все задачи уже записаны.": "All tasks are already stored.",
  "Задачи записаны и перечитаны. Итоговый отчёт содержит путь backup.": "Tasks saved and read back. The final report contains the backup path.",
  " Не удалось сохранить отчёт. Повтори его сохранение.": " Could not save the report. Try saving it again.",
  "Сейчас: ": "Now: ",
  " · ещё в работе: ": " · more running: ",
  "Ближайший шаг: ": "Next step: ",
  "Все сохранённые шаги выполнены: ": "All saved steps completed: ",
  "Ждём ответа: ": "Waiting for a response: ",
  " · ещё ожидают: ": " · more waiting: ",
  "Шаги и результат · выполнено ": "Steps and result · completed ",
  " из ": " of ",
  "Статус шага: ": "Step status: ",
  "Последний импортированный отчёт ": "Latest imported report ",
  "Токены: ": "Tokens: ",
  ". Стоимость не сообщена.": ". Cost not reported.",
  "Попытка ": "Attempt ",
  " подготовлена. Отчёта о выполнении нет. Расходы неизвестны.": " prepared. No execution report. Usage unknown.",
  "Последнее событие ": "Latest event ",
  "Импортированный отчёт — ": "Imported report — ",
  ". Последнее наблюдение: ": ". Last observed: ",
  ". Источник отчёта: ": ". Report source: ",
  ". Основание: ": ". Evidence: ",
  " • операция: ": " • operation: ",
  " • ожидание: ": " • waiting for: ",
  " • результат: ": " • result: ",
  "Рекомендация в «Сегодня»": "Recommendation in Today",
  "Учитываем текущую работу, даты и важность задач, время суток и отметки рутин. Запуск — только по твоему нажатию.": "Uses current work, task dates and importance, time of day and routine check-ins. Starts only when you click.",
  "Предлагать, чем заняться": "Suggest what to do",
  "Задачи": "Tasks",
  "Рутины": "Routines",
  "Отметки рутин": "Routine check-ins",
  "Раскрывать отмеченные рутины": "Expand checked routines",
  "Рутины и правила": "Routines and rules",
  "Вид календаря": "Calendar view",
  "Эти изменения сохраняются кнопкой «Сохранить календарь».": "Save these changes with Save calendar.",
  "Стадии: ": "Stages: ",
  "стадия ": "stage ",
  "Стадия ": "Stage ",
  "Выше: ": "Move up: ",
  "Ниже: ": "Move down: ",
  "Удалить стадию: ": "Delete stage: ",
  "Добавить стадию: ": "Add stage: ",
  "Убрать новый процесс: ": "Remove new process: ",
  "Стадия «": "Stage “",
  "» теперь ": "” is now at position ",
  "-я.": ".",
  "» будет удалена после сохранения.": "” will be deleted after saving.",
  "Процессов: ": "Processes: ",
  "Ожидают отправки: ": "Pending to send: ",
  " · Конфликты: ": " · Conflicts: ",
  "Последний успешный обмен: ": "Last successful exchange: ",
  "Изменено: ": "Updated: ",
  "Сохранено версий: ": "Saved versions: ",
  "Выбрать папку ": "Choose folder ",
  "Проверить папку ": "Check folder ",
  "Проверено ": "Checked ",
  ". Только метаданные; содержимое не импортировано.": ". Metadata only; contents were not imported.",
  "Источник: ": "Source: ",
  " • опубликован ": " • published ",
  " • снимок ": " • snapshot ",
  " • подзадача ": " • subtask ",
  " • источник: ": " • source: ",
  "Экспорт сохранён и проверен: ": "Export saved and verified: ",
  "Не удалось сохранить экспорт. ": "Could not save the export. ",
  " Повтори сохранение; импорт пока недоступен.": " Try saving again; import is unavailable until then.",
  "Было: ": "Before: ",
  "Станет: ": "After: ",
  "Личная задача. Проекты: ": "Personal task. Projects: ",
  "В архив: ": "Archive: ",
  " (версия ": " (version ",
  "Понедельник": "Monday",
  "Воскресенье": "Sunday",
  "Месяц": "Month",
  "Неделя": "Week",
  "День": "Day",
  "Обычная": "Comfortable",
  "Компактная": "Compact",
  "Сегодня": "Today",
  "Календарь": "Calendar",
  "Этапы задач": "Task stages",
  "Подключения": "Connections",
  "О приложении": "About",
  "Не удалось загрузить настройки календаря.": "Could not load calendar settings.",
  "Ожидает безопасного применения": "Awaiting safe application",
  "Сохранена альтернативная версия": "Alternative version saved",
  "Данные и источники": "Data and sources",
  "Выбери папку и проверь структуру перед сохранением. Файлы не читаются, данные не переносятся. Видимость и размещение применяются к разделам источников в области задач. Автоматического обмена нет.": "Choose a folder and check its structure before saving. Files are not read and data is not transferred. Visibility and placement apply to source sections in Tasks. There is no automatic exchange.",
  "Предлагаемая структура:\n<app>-data/manifest.json\n<app>-data/projects/\n<app>-data/tasks/\n<app>-data/runs/\nCredentials и sessions хранятся отдельно.\nGit local/private — предпочтение, репозиторий не создан.": "Suggested structure:\n<app>-data/manifest.json\n<app>-data/projects/\n<app>-data/tasks/\n<app>-data/runs/\nCredentials and sessions are stored separately.\nLocal/private Git is a preference; no repository was created.",
  "Проверка не удалась: требуется существующая локальная папка без ссылок и неверных типов. Содержимое не читалось.": "Check failed: an existing local folder without links or invalid types is required. Contents were not read.",
  "Выбор папки недоступен. Введи абсолютный путь и проверь его.": "Folder picker unavailable. Enter an absolute path and check it.",
  "Tasks • перед локальными задачами": "Tasks • before local tasks",
  "Projects • после локальных задач": "Projects • after local tasks",
  "Не удалось сохранить выбор. Повтори позже.": "Could not save your choice. Try again later.",
  "Проверка результата ИИ": "AI result review",
  "Замечание для доработки": "Rework comment",
  "История решений": "Decision history",
  "Принять": "Accept",
  "Доработать": "Request rework",
  "Обновить результат": "Refresh result",
  "Повторить отправку": "Retry submission",
  "Отменить решение": "Cancel decision",
  "Решение не отправлено. Замечание осталось в черновике.": "Decision not submitted. The comment remains in the draft.",
  "Ожидает решения": "Awaiting decision",
  "Результат принят": "Result accepted",
  "Доработка подтверждена. Ожидает передачи исполнителю; работа ещё не началась.": "Rework confirmed. Awaiting dispatch to the executor; work has not started.",
  "В работе · подтверждено исполнителем": "In progress · confirmed by the executor",
  "Решение сохранено в локальной очереди. Подтверждения сервиса и запуска нет.": "Decision saved in the local queue. No service acknowledgement or start confirmation.",
  "Исход отправки неизвестен. Повтор использует то же решение.": "Submission outcome unknown. Retrying uses the same decision.",
  "Результат обновлён. Проверь ревизию перед решением.": "Result refreshed. Check the revision before deciding.",
  "Результат недоступен. Решение не отправлено.": "Result unavailable. Decision not submitted.",
  "Добавь замечание для доработки (до 8000 символов).": "Add a rework comment (up to 8000 characters).",
  "Решение подтверждено сервисом.": "Decision acknowledged by the service.",
  "Результат изменился (409). Обнови результат и проверь новую ревизию. Замечание сохранено.": "Result changed (409). Refresh it and check the new revision. Your comment is preserved.",
  "Исход отправки неизвестен. Замечание сохранено; повтор отправит исходное решение.": "Submission outcome unknown. Your comment is preserved; retrying submits the original decision.",
  "Дождись завершения отправки решения.": "Wait for the decision submission to finish.",
  "Не удалось проверить импорт сна. Повтори попытку.": "Could not check sleep import. Try again.",
  "Сон импортируется из Health Connect на телефоне Android и приходит сюда через синхронизацию.": "Sleep is imported from Health Connect on an Android phone and arrives here through sync.",
  "Health Connect недоступен. Установи или обнови его на телефоне.": "Health Connect unavailable. Install or update it on your phone.",
  "Разреши Cicada читать сон в Health Connect. Импортированные ранее записи сохранены.": "Allow Cicada to read sleep in Health Connect. Previously imported records are preserved.",
  "Заверши системный запрос Health Connect, затем проверь сон. Разрешение ещё не подтверждено.": "Complete the Health Connect system prompt, then check sleep. Permission is not confirmed yet.",
  "Для чтения сна открой Cicada на телефоне.": "Open Cicada on your phone to read sleep.",
  "Последний импорт сна не завершён. Сохранённые записи не потеряны; повтори попытку.": "The last sleep import did not finish. Stored records are preserved; try again.",
  "Доступ разрешён. Первый импорт сна ещё не подтверждён.": "Access allowed. The first sleep import is not confirmed yet.",
  "В Health Connect не найдено записей сна. Проверь, что Samsung Health или другое приложение передаёт туда сон.": "No sleep records found in Health Connect. Check that Samsung Health or another app sends sleep there.",
  "Сон": "Sleep",
  "Проверяем Health Connect…": "Checking Health Connect…",
  "Разрешить чтение сна": "Allow sleep access",
  "Проверить сон сейчас": "Check sleep now",
  "Повторить проверку": "Retry check",
  "Проверяем записи сна…": "Checking sleep records…",
  "Разрешить чтение в фоне": "Allow background access",
  "Фоновое чтение разрешено. Android определяет время запуска; обновление может задерживаться.": "Background access allowed. Android controls the schedule; updates may be delayed.",
  "Фоновое чтение не разрешено. Пока сон проверяется при открытом приложении.": "Background access not allowed. Sleep is checked while the app is open.",
  "На этом телефоне Health Connect не поддерживает чтение в фоне. Сон проверяется при открытом Cicada.": "Health Connect does not support background access on this phone. Sleep is checked while Cicada is open.",
  "После перерыва повторно проверены последние 30 дней. Более ранние записи сохранены, но изменения в них пока не подтверждены источником.": "The last 30 days were checked again after a break. Earlier records are preserved, but changes to them have not been confirmed by the source yet.",
  "Не удалось проверить импорт. Повтори попытку.": "Could not check import. Try again.",
  "Прогулки и шаги импортируются из Health Connect на телефоне Android и приходят сюда через синхронизацию.": "Walks and steps are imported from Health Connect on an Android phone and arrive here through sync.",
  "Заверши системный запрос Health Connect, затем проверь импорт. Разрешение ещё не подтверждено.": "Complete the Health Connect system prompt, then check import. Permission is not confirmed yet.",
  "прогулок": "walks",
  "шагов": "steps",
  "прогулки": "walks",
  "шаги": "steps",
  "В Health Connect не найдено прогулок с типом walking. Cicada не выводит прогулки из одних шагов.": "No walking sessions found in Health Connect. Cicada does not infer walks from steps alone.",
  "В Health Connect не найдено дневных итогов шагов. Пустой день не считается нулевым итогом.": "No daily step totals found in Health Connect. An empty day is not treated as a zero total.",
  "Прогулки и шаги": "Walks and steps",
  "Прогулки": "Walks",
  "Шаги": "Steps",
  "Разрешить чтение прогулок и шагов": "Allow walks and steps access",
  "Проверить прогулки и шаги сейчас": "Check walks and steps now",
  "Проверяем прогулки…": "Checking walks…",
  "Проверяем шаги…": "Checking steps…",
  "Разрешить недостающий доступ": "Allow missing access",
  "Фоновое чтение не разрешено. Пока данные проверяются при открытом приложении.": "Background access not allowed. Data is checked while the app is open.",
  "На этом телефоне Health Connect не поддерживает чтение в фоне. Данные проверяются при открытом Cicada.": "Health Connect does not support background access on this phone. Data is checked while Cicada is open.",
  "Результат · ревизия ": "Result · revision ",
  " · версия задачи ": " · task version ",
  " · результат ": " · result ",
  "Импортировано записей сна: ": "Sleep records imported: ",
  "Последняя проверка сна: ": "Last sleep check: ",
  "Для чтения ": "To read ",
  " открой Cicada на телефоне.": " open Cicada on your phone.",
  "Последний импорт ": "Last import of ",
  " не завершён. Сохранённые записи не потеряны; повтори попытку.": " did not finish. Stored records are preserved; try again.",
  "Разреши Cicada читать ": "Allow Cicada to read ",
  " в Health Connect. Ранее импортированные записи сохранены.": " in Health Connect. Previously imported records are preserved.",
  "Доступ к ": "Access to ",
  " разрешён. Первый импорт ещё не подтверждён.": " allowed. The first import is not confirmed yet.",
  "Импортировано прогулок: ": "Walks imported: ",
  "Импортировано дневных итогов шагов: ": "Daily step totals imported: ",
  "Последняя проверка прогулок и шагов: ": "Last walks and steps check: ",
  "Запланировано": "Planned",
  "Проверка": "Checking",
  "Нужно решение": "Decision needed",
  "Готово": "Done",
  "Отменено": "Cancelled",
  "Неизвестно": "Unknown",
  "Свежее наблюдение": "Fresh observation",
  "Устаревшее наблюдение": "Stale observation",
  "Свежесть неизвестна": "Observation freshness unknown",
  " Сохранение ": " Saving ",
  " не подтверждено; черновик остался в форме.": " is unconfirmed; the draft remains in the form.",
  "Нужен хотя бы один процесс.": "At least one process is required.",
  "У процесса неверный идентификатор. Отмени изменения и повтори.": "The process identifier is invalid. Discard changes and retry.",
  "Укажи название процесса.": "Enter a process name.",
  "Добавь хотя бы одну стадию.": "Add at least one stage.",
  "У стадии неверный идентификатор. Удали её и добавь снова.": "The stage identifier is invalid. Remove it and add it again.",
  "Укажи название стадии.": "Enter a stage name.",
  "Неподдерживаемый формат процессов. Сохранение остановлено, чтобы не потерять данные.": "Unsupported process format. Saving stopped to preserve data.",
  "Процессы изменены на другом устройстве. Нажми «Отменить изменения», чтобы загрузить новую версию, и повтори.": "Processes changed on another device. Use Discard changes to load the new version, then retry.",
  "Можно сохранить до 20 процессов.": "You can save up to 20 processes.",
  "Сократи название процесса до 80 символов.": "Shorten the process name to 80 characters.",
  "Сократи название стадии до 80 символов.": "Shorten the stage name to 80 characters.",
  "Назови процесс.": "Name the process.",
  "У стадии неверный идентификатор. Отмени изменения и повтори.": "The stage identifier is invalid. Discard changes and retry.",
  "Назови стадию или удали её.": "Name the stage or remove it.",
  "В процессе можно держать до 30 стадий.": "A process can have up to 30 stages.",
  "Настройки": "Settings"
};
export function copyForLanguage(language = 'ru') {
  const en = typeof language === 'string' && language.toLowerCase().startsWith('en');
  const copy = value => en && Object.hasOwn(english, value) ? english[value] : value;
  copy.locale = en ? 'en' : 'ru-RU';
  return copy;
}
export function createUiCopy(document) { return copyForLanguage(document.documentElement.lang); }
